info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths: {}
components:
  schemas:
    PlannedCrossNewRequest:
      type: object
      properties:
        additionalInfo:
          additionalProperties:
            type: string
          description: Additional arbitrary info
          type: object
        crossingProjectDbId:
          description: the unique identifier for a crossing project
          type: string
          example: 696d7c92
        crossingProjectName: 
          description: the human readable name for a crossing project
          type: string
          example: my_Crosses_2018
        plannedCrossName: 
          description: the human readable name for a planned cross
          type: string
          example: my_Crosses_2018_01
        crossType: 
          description: the type of cross
          type: string
          enum:
          - BIPARENTAL
          - SELF
          - OPEN_POLLINATED
          - BULK
          - BULK_SELFED
          - BULK_OPEN_POLLINATED
          - DOUBLE_HAPLOID
          example: BIPARENTAL
        status: 
          description: The status of this planned cross. Is it waiting to be performed ('TODO'), has it been completed successfully ('DONE'), or has it not been done on purpose ('SKIPPED').
          type: string
          enum:
          - TODO
          - DONE
          - SKIPPED
          example: TODO
        parent1: 
          $ref: '#/components/schemas/CrossParent'
        parent2: 
          $ref: '#/components/schemas/CrossParent'
        externalReferences: 
          $ref: '#/components/schemas/ExternalReferences'
          