info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths: {}
components:
  schemas:
    PlannedCross:
      allOf:
        - $ref: '#/components/schemas/PlannedCrossNewRequest'
        - type: object
          x-brapi-metadata:
            primaryModel: true
            module: BrAPI-Germplasm
            title: PlannedCross
            description: Information regarding the intention to mate specific organisms together to produce offspring with desired traits. A PlannedCross becomes an actual Cross when the desired mating event actually occurs in the field. 
          required:
          - plannedCrossDbId
          properties:
            plannedCrossDbId:
              description: the unique identifier for a planned cross
              type: string
              example: c8905568