info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths:
  /search/allelematrix/{searchResultsDbId}:
    get:
      summary: Get the results of a Allele Matrix search request
      description: |-
        Use this endpoint to retrieve a two dimensional matrix of genotype data. The response structure is based on the VCF format, with the enhanced ability to slice and merge data sets. This allows the user to return the subset of data they are interested in, without having to download the entire genotype file.
        <br/>Each row of data (outer array) corresponds to a variant definition, and each column (inner array) corresponds to a callSet. 
        <br/>Clients should submit a search request using the corresponding `POST /search/allelematrix` endpoint. Search requests allow a client to send a complex query for data. However, the server may not respond with the search results immediately. If a server needs more time to process the request, it might respond with a `searchResultsDbId`. Use this endpoint to retrieve the results of the search. 
        <br/>Review the <a target="_blank" href="https://wiki.brapi.org/index.php/Search_Services#POST_Search_Entity">Search Services documentation</a> for additional implementation details.
      parameters:
      - $ref: '#/components/parameters/searchResultsDbId'
      - $ref: '#/components/parameters/authorizationHeader'
      responses:
        '202': 
          $ref: '#/components/responses/202AcceptedSearchResponse' 
        '200':
          $ref: '#/components/responses/AlleleMatrixResponse'
        '400':
          $ref: '#/components/responses/400BadRequest'
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '403':
          $ref: '#/components/responses/403Forbidden'
      tags:
        - Genotype-Matrix-Redesign