info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths: {}
components:
  parameters:
    searchResultsDbId:
      description: Unique identifier which references the search results
      in: path
      name: searchResultsDbId
      required: true
      schema:
        type: string
    preview:
      name: preview
      description: |- 
            Default Value = false
            <br/>
            If 'preview' is set to true, then the server should only return the lists of 'callSetDbIds', 
            'variantDbIds', and 'variantSetDbIds'. The server should not return any matrix data. This
            is intended to be a preview and give the client a sense of how large the matrix returned will be
            <br/>
            If 'preview' is set to false or not set (default), then the server should return all the matrix
            data as requested.
      in: query
      required: false
      schema:
        type: boolean
    dataMatrixNames:
      name: dataMatrixNames
      description: dataMatrixNames is a comma seperated list of names (ie 'Genotype, Read Depth' etc). This list controls which data matrices are returned in the response.
      in: query
      required: false
      schema:
        type: string
    dataMatrixAbbreviations:
      name: dataMatrixAbbreviations
      description: dataMatrixAbbreviations is a comma seperated list of abbreviations (ie 'GT, RD' etc). This list controls which data matrices are returned in the response.
      in: query
      required: false
      schema:
        type: string
    callSetDbId:
      name: callSetDbId
      description: The ID of the `CallSet` to be retrieved.
      in: query
      required: false
      schema:
        type: string
    variantDbId:
      name: variantDbId
      description: The ID of the `Variant` to be retrieved.
      in: query
      required: false
      schema:
        type: string
    variantSetDbId:
      name: variantSetDbId
      description: The ID of the `VariantSet` to be retrieved.
      in: query
      required: false
      schema:
        type: string
    expandHomozygotes:
      name: expandHomozygotes
      description: Should homozygotes be expanded (true) or collapsed into a single occurrence (false)
      in: query
      required: false
      schema:
        type: boolean
    unknownString:
      name: unknownString
      description: The string to use as a representation for missing data
      in: query
      required: false
      schema:
        type: string
    sepPhased: 
      name: sepPhased
      description: The string to use as a separator for phased allele calls
      in: query
      required: false
      schema:
        type: string
    sepUnphased: 
      name: sepUnphased
      description: The string to use as a separator for unphased allele calls
      in: query
      required: false
      schema:
        type: string
    germplasmPUI:
        name: germplasmPUI
        description: Permanent unique identifier (DOI, URI, etc.)
        in: query
        required: false
        schema:
          type: string
    germplasmDbId:
        name: germplasmDbId
        description: Internal database identifier
        in: query
        required: false
        schema:
          type: string
    germplasmName:
        name: germplasmName
        description: Name of the germplasm
        in: query
        required: false
        schema:
          type: string
    positionRange:
        name: positionRange
        description: |-
          The postion range to search
          <br/>
          Uses the format "contig:start-end" where "contig" is the chromosome or contig name, "start" is 
          the starting position of the range, and "end" is the ending position of the range
        in: query
        required: false
        schema:
          type: string
