info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths: {}
components:
  schemas:
    MetabolomicsProtocolNewRequest:
      type: object
      properties:
        additionalInfo:
          additionalProperties:
            type: string
          description: Additional arbitrary info
          type: object
        externalReferences: 
          $ref: '#/components/schemas/ExternalReferences'
        documentationURL:
          description: description
          format: uri
          type: string
          example: https://wiki.brapi.org
        headerColumns:
          description: Column definitions for any matrix with this protocol 
          type: array
          items:
            $ref: '#/components/schemas/Metabolite'
        phenotypeUnits: 
          description: Free text, e.g. relative abundance, BLUP, drBLUP, concentration (specify units, e.g. ug/g)
          type: string
          example: relative abundance
        publications: 
          description: Relevant publication(s), DOI with details
          type: array
          items:
            type: string
            example: https://doi.org/10.1093/example
        equipment: 
          type: object
          properties:
            analysisType: 
              description: MS or NMR. If NMR is selected, the rest of Equipment are not needed
              type: string
              enum: [MS, NMR]
              example: MS
            chromatographyType:  
              description: description
              type: string
              enum: [LC, GC]
              example: LC
            chromatographySystem:  
              description: User free text to specify brand of chromotography system
              type: string
              example: Waters Acuity UPLC
            chromatographyColumn:  
              description: User free text to specify brand of chromotography column
              type: string
              example: Waters 164 Acquity UPLC CSH Phenyl Hexyl column (1.7 IM, 1.0 x 100 mm)
            msInstrumentName:  
              description: User free text to specify brand of MS system
              type: string
              example: Waters Xevo G2 TOF-MS
            msInstrumentType:  
              description: User free text, e.g. time of flight (TOF), triple quadropole
              type: string
              example: TOF
            msType:  
              description: Electron Ionization (EI), Electrospray Ionization (ESI), Atmospheric Pressure Chemical Ionization (APCI), Matrix Assisted Laser Desorption Ionization (MALDI), Other (please specify below)
              type: string
              example: ESI
            msIonMode:  
              description: Negative, Positive, Both
              type: string
              example: Positive
        protocol:
          type: object
          properties:
            sampleCollection: 
              description: the tissue, time point, if the sample was frozen
              type: string
              example: seed, mature
            sampleExtraction: 
              description: the extraction protocol used
              type: string
              example: biphasic, polar extract with methanol from 100 mg of tissue
            chromatography: 
              description: the LC protocol, instrument settings, calibration procedure
              type: string
              example: gradient of solvent A (2mM ammonium hydroxide and 0.1% formic acid) to solvent B (Acetonitrile, 0.1% formic acid)
            massSpectrometry: 
              description: instrument settings, calibration procedure
              type: string
              example: scanning 50-2000 m/z at 0.2 seconds per scan, alternating between MS (6 V collision energy) and MSE mode (15-30 V ramp)
            rawDataTransformation: 
              description: the LCMS machine files were transformed into peak area
              type: string
              example: XCMS, centWave, RamCLUSTR
            metaboliteIdentification: 
              description: metabolite annotations were assigned to peaks
              type: string
              example: RAMSearch, MSFinder
            phenotype: 
              description: BLUPs were calculated from the peak area
              type: string
              example: NA
