info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths: {}
components:
  schemas:
    Event:
      type: object 
      required: 
      - eventDbId
      - eventType
      properties:
        additionalInfo:
          additionalProperties:
            type: string
          description: Additional arbitrary info
          type: object
        eventDbId:
          description: Internal database identifier
          type: string
          example: 8566d4cb
        eventType:
          description: |-
            General category for this event (e.g. fertilizer, irrigation, tillage). Each eventType should correspond to exactly one eventTypeDbId, if provided.
            <br/>ICASA Management events allow for the following types: planting, fertilizer, irrigation, tillage, organic_material, harvest, bed_prep, inorg_mulch, inorg_mul_rem, chemicals, mowing, observation, weeding, puddling, flood_level, other
            <br/>MIAPPE V1.1 (DM-65) Event type - Short name of the event.
          type: string
          example: tillage
        eventTypeDbId:
          description: |-
            An identifier for this event type, in the form of an ontology class reference
            <br/>ICASA Management events allow for the following types: planting, fertilizer, irrigation, tillage, organic_material, harvest, bed_prep, inorg_mulch, inorg_mul_rem, chemicals, mowing, observation, weeding, puddling, flood_level, other
            <br/>MIAPPE V1.1 (DM-66) Event accession number - Accession number of the event type in a suitable controlled vocabulary (Crop Ontology).
          type: string
          example: 4e7d691e
        eventDescription: 
          description: |-
            A detailed, human-readable description of this event
            <br/>MIAPPE V1.1 (DM-67) Event description - Description of the event, including details such as amount applied and possibly duration of the event. 
          type: string
          example: A set of plots was watered
        studyDbId: 
          description: The study in which the event occurred
          type: string
          example: 2cc2001f
        studyName: 
          description: The human readable name of a study
          type: string
          example: 2cc2001f
        observationUnitDbIds: 
          description: A list of the affected observation units. If this parameter is not given, it is understood that the event affected all units in the study
          items:
            type: string
          type: array
          example: ['8439eaff', 'd7682e7a', '305ae51c']
        date:
          type: object
          properties:
            discreteDates:
              description: |-
                A list of dates when the event occurred
                <br/>MIAPPE V1.1 (DM-68) Event date - Date and time of the event.
              items:
                format: date-time
                type: string
              type: array
              example: ['2018-10-08T18:15:11Z', '2018-11-09T18:16:12Z', '2018-11-19T18:16:12Z']
            startDate:
              description: |-
                The begining of a continous or regularly repetitive event
                <br/>MIAPPE V1.1 (DM-68) Event date - Date and time of the event.
              format: date-time
              type: string
              example: '2018-10-08T18:15:11Z'
            endDate:
              description: |-
                The end of a continous or regularly repetitive event
                <br/>MIAPPE V1.1 (DM-68) Event date - Date and time of the event.
              format: date-time
              type: string
              example: '2018-10-08T18:15:11Z'
        eventParameters: 
          description: A list of objects describing additional event parameters. Each of the following accepts a human-readable value or URI
          type: array 
          items: 
            type: object
            properties:
              name:
                description: |-
                  The full name of an event parameter

                  ICASA "Variable_Name"
                type: string
                example: tillage_implement
              code:
                description: |-
                  The shortened code name of an event parameter

                  ICASA "Code_Display"
                type: string
                example: tiimp
              unit:
                description: |-
                  The unit or data type of the value. 
                  <br>If the 'value' comes from a standardized vocabulary or an encoded list of values, then 'unit' should be 'code'. 
                  <br>If the 'value' IS NOT a number, then 'unit' should specify a data type eg. 'text', 'boolean', 'date', etc. 
                  <br>If the value IS a number, then 'unit' should specify the units used eg. 'ml', 'cm', etc
                  <br>ICASA "Unit_or_type"
                type: string
                example: code
              value:
                description: The single value of this event parameter. This single value is accurate for all the dates in the date range. If 'value' is populated then 'valuesByDate' should NOT be populated.
                type: string
                example: TI001
              valuesByDate:
                description: An array of values corrisponding to each timestamp in the 'discreteDates' array of this event. The 'valuesByDate' array should exactly match the size of the 'discreteDates' array. If 'valuesByDate' is populated then 'value' should NOT be populated.
                type: array
                items:
                  type: string
                example: ['20', '50', '40']
              parameterDescription:
                description: A human readable description of this event parameter. This description is ussually associated with the 'name' and 'code' of an event parameter.
                type: string
                example: Implement or tool used for tillage
              codeValueDescription:
                description: If the event parameter 'unit' field is 'code', then use 'codeValueDescription' to add a human readable description to the value.
                type: string
                example: Standard V-Ripper (TI001)
          example:
          - name: "tillage_implement"
            code: "tiimp"
            parameterDescription: Implement or tool used for tillage
            unit: "code"
            value: "TI001"
            codeValueDescription: Standard V-Ripper (TI001)
          - name: "tillage_operations_depth"
            code: "tidep"
            parameterDescription: Tillage operations depth in centimeters
            unit: "cm"
            valuesByDate: ['20', '50', '40']
          - name: "till_mix_effectiveness"
            code: "timix"
            parameterDescription: Tillage operations mixing effectiveness
            unit: "percent"
            value: "50"

