info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths:
  /nirs/{nirsProtocolDbId}:
    get:
      summary: Get a NIRS Protocol by Id
      description: Get a single NIRS Protocol by Id. This can be used to quickly get the details of a NIRSProtocol when you have the Id from another entity. 
      parameters:
      - name: nirsProtocolDbId
        description: Filter by the common crop name. Exact match.
        in: path
        required: true
        schema:
          type: string
      - $ref: '#/components/parameters/authorizationHeader'
      responses:
        '200':
          $ref: '#/components/responses/NIRSProtocolSingleResponse'
        '400':
          $ref: '#/components/responses/400BadRequest'
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '403':
          $ref: '#/components/responses/403Forbidden'
      tags:
      - NIRS
    put:
      summary: Update an existing NIRS Protocol
      description: Update the details of an existing breeding NIRS Protocol. 
      parameters:
      - name: nirsProtocolDbId
        description: Filter by the common crop name. Exact match.
        in: path
        required: true
        schema:
          type: string
      - $ref: '#/components/parameters/authorizationHeader'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NIRSProtocolNewRequest'
      responses:
        '200':
          $ref: '#/components/responses/NIRSProtocolSingleResponse'
        '400':
          $ref: '#/components/responses/400BadRequest'
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '403':
          $ref: '#/components/responses/403Forbidden'
      tags:
      - NIRS
components:
  responses:
    NIRSProtocolSingleResponse:
      content:
        application/json:
          schema:
            title: NIRSProtocolSingleResponse
            properties:
              '@context':
                $ref: '#/components/schemas/Context'
              metadata:
                $ref: '#/components/schemas/metadata'
              result:
                $ref: '#/components/schemas/NIRSProtocol'
            required:
            - metadata
            - result
            type: object
      description: OK
      headers: {}
