info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths:
  /programs/{programDbId}:
    get:
      summary: Get a breeding Program by Id
      description: Get a single breeding Program by Id. This can be used to quickly get the details of a Program when you have the Id from another entity. 
      parameters:
      - name: programDbId
        description: Filter by the common crop name. Exact match.
        in: path
        required: true
        schema:
          type: string
      - $ref: '#/components/parameters/authorizationHeader'
      responses:
        '200':
          $ref: '#/components/responses/ProgramSingleResponse'
        '400':
          $ref: '#/components/responses/400BadRequest'
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '403':
          $ref: '#/components/responses/403Forbidden'
      tags:
      - Programs
    put:
      summary: Update an existing Program
      description: Update the details of an existing breeding Program. 
      parameters:
      - name: programDbId
        description: Filter by the common crop name. Exact match.
        in: path
        required: true
        schema:
          type: string
      - $ref: '#/components/parameters/authorizationHeader'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProgramNewRequest'
      responses:
        '200':
          $ref: '#/components/responses/ProgramSingleResponse'
        '400':
          $ref: '#/components/responses/400BadRequest'
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '403':
          $ref: '#/components/responses/403Forbidden'
      tags:
      - Programs
components:
  responses:
    ProgramSingleResponse:
      content:
        application/json:
          schema:
            title: ProgramSingleResponse
            properties:
              '@context':
                $ref: '#/components/schemas/Context'
              metadata:
                $ref: '#/components/schemas/metadata'
              result:
                $ref: '#/components/schemas/Program'
            required:
            - metadata
            - result
            type: object
      description: OK
      headers: {}
