info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths: {}
components:
  schemas:
    SeedLotNewRequest:
      type: object
      required:
      - seedLotName
      properties:
        additionalInfo:
          additionalProperties:
            type: string
          description: A free space containing any additional information related to a particular object. A data source may provide any JSON object, unrestricted by the BrAPI specification.
          type: object
        seedLotName:
          description: A human readable name for this Seed Lot 
          type: string
          example: Seed Lot Alpha
        seedLotDescription:
          description: A general description of this Seed Lot
          type: string
          example: This is a description of a seed lot
        sourceCollection:
          description: The description of the source where this material was originally collected (wild, nursery, etc)
          type: string
          example: nursery
        programDbId:
          description: The unique DbId of the breeding program this Seed Lot belongs to
          type: string
          example: e972d569
        programName:
          description: The human readable name of the breeding program this Seed Lot belongs to
          type: string
          example: Tomatillo_Breeding_Program
        locationDbId:
          description: The unique identifier for a Location
          type: string
          example: 3cfdd67d
        locationName:
          description: A human readable name for a location
          type: string
          example: Location 1
        storageLocation:
          description: Description the storage location 
          type: string
          example: The storage location is an massive, underground, bunker.
        createdDate:
          description: The time stamp for when this seed lot was created
          type: string
          format: date-time
        lastUpdated:
          description: The timestamp for the last update to this Seed Lot (including transactions)
          type: string
          format: date-time
        contentMixture:
          description: |-
            The mixture of germplasm present in the seed lot.
            <br/>
            If this seed lot only contains a single germplasm, the response should contain the name 
            and DbId of that germplasm with a mixturePercentage value of 100
            <br/>
            If the seed lot contains a mixture of different germplasm, the response should contain 
            the name and DbId every germplasm present. The mixturePercentage field should contain 
            the ratio of each germplasm in the total mixture. All of the mixturePercentage values 
            in this array should sum to equal 100.
          type: array
          items:
            type: object
            properties:
              germplasmDbId:
                description: The unique DbId of the Germplasm contained in this Seed Lot 
                type: string
                example: 029d705d
              germplasmName:
                description: The human readable name of the Germplasm contained in this Seed Lot 
                type: string
                example: A0000003
              crossDbId:
                description: The unique DbId for a cross contained in this seed lot
                type: string
                example: d105fd6f
              crossName:
                description: The human readable name for a cross contained in this seed lot
                type: string
                example: my_Crosses_2018_01
              mixturePercentage:
                description: The percentage of the given germplasm in the seed lot mixture.   
                type: integer
                example: 100
        amount:
          description: The current balance of the amount of material in a SeedLot. Could be a count (seeds, bulbs, etc) or a weight (kg of seed).
          type: number
          example: 561
        units:
          description: A description of the things being counted in a SeedLot (seeds, bulbs, kg, tree, etc)
          type: string
          example: seeds
        externalReferences: 
          $ref: '#/components/schemas/ExternalReferences'
          
