info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths: {}
components:
  schemas:
    SeedLotTransaction:
      allOf:
      - $ref: '#/components/schemas/SeedLotTransactionNewRequest'
      - type: object
        properties: 
          transactionDbId:
            description: Unique DbId for the Seed Lot Transaction
            type: string
            example: 28e46db9
        required:
        - transactionDbId
