info: 
  title: BrAPI
  version: ''
openapi: 3.0.0
paths: {}
components:
  schemas:
    SeedLotTransaction:
      allOf:
      - $ref: '#/components/schemas/SeedLotTransactionNewRequest'
      - type: object
        x-brapi-metadata:
          primaryModel: true
          module: BrAPI-Germplasm
          title: SeedLotTransaction
          description: The record of an event where material was moved in or out of a particular SeedLot
        properties: 
          transactionDbId:
            description: Unique DbId for the Seed Lot Transaction
            type: string
            example: 28e46db9
        required:
        - transactionDbId
