info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths: {}
components:
  schemas:
    SeedLotTransactionNewRequest:
      type: object
      properties:
        additionalInfo:
          additionalProperties:
            type: string
          description: Additional arbitrary info
          type: object
        transactionDescription:
          description: A general description of this Seed Lot Transaction
          type: string
          example: f9cd88d2
        transactionTimestamp:
          description: The time stamp for when the transaction occurred
          type: string
          format: date-time
        toSeedLotDbId:
          description: The identifier for the Seed Lot being transfered into
          type: string
          example: 59339b90
        fromSeedLotDbId:
          description: The identifier for the Seed Lot being transfered out of
          type: string
          example: 11eef13b
        amount: 
          description: The amount of units being transfered. Could be a count (seeds, bulbs, etc) or a weight (kg of seed).
          type: number
          example: 45
        units:
          description: Description of the things being transfered in this transaction (seeds, bulbs, kg, etc)
          type: string
          example: seeds
        externalReferences: 
          $ref: '#/components/schemas/ExternalReferences'
          

