info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths: {}
components:
  schemas:
    Variant:
      type: object
      description: |-
        A `Variant` represents a change in DNA sequence relative to some reference.
        For example, a variant could represent a SNP or an insertion.
        Variants belong to a `VariantSet`.
        This is equivalent to a row in VCF.
      properties:
        alternate_bases:
          description: The bases that appear instead of the reference bases. Multiple alternate alleles are possible.
          items:
            type: string
          type: array
          example: ['TAGGATTGAGCTCTATAT']
        additionalInfo:
          additionalProperties:
            type: string
          description: Additional arbitrary info
          type: object
        externalReferences: 
          $ref: '#/components/schemas/ExternalReferences'
        ciend:
          items:
            type: integer
          description: Similar to "cipos", but for the variant's end position (which is derived from start + svlen).
          example: [ -1000, 0 ]
          type: array
        cipos:
          items:
            type: integer
          description: |-
            In the case of structural variants, start and end of the variant may not
            be known with an exact base position. "cipos" provides an interval with
            high confidence for the start position. The interval is provided by 0 or
            2 signed integers which are added to the start position.
            Based on the use in VCF v4.2
          example: [ -12000, 1000 ]
          type: array
        created:
          description: The timestamp when this variant was created.
          type: string
          format: date-time
        end:
          description: |-
            This field is optional and may be ignored if there is no relevant map or reference to be associated with.
          
            The end position (exclusive), resulting in [start, end) closed-open interval. This is typically calculated 
            by `start + referenceBases.length`.
          type: integer
          example: 518
        filtersApplied:
          description: True if filters were applied for this variant. VCF column 7 "FILTER" any value other than the missing value.
          format: boolean
          type: boolean
          example: True
        filtersFailed:
          description: Zero or more filters that failed for this variant. VCF column 7 "FILTER" shared across all alleles in the same VCF record.
          items:
            type: string
          type: array
          example: ['d629a669', '3f14f578']
        filtersPassed:
          description: True if all filters for this variant passed. VCF column 7 "FILTER" value PASS.
          format: boolean
          type: boolean
          example: True
        variantDbId:
          description: The variant ID.
          type: string
          example: 628e89c5
        variantNames:
          description: Names for the variant, for example a RefSNP ID.
          items:
            type: string
          type: array
          example: ['RefSNP_ID_1', '06ea312e']
        referenceDbId:
          description: The unique identifier for a Reference
          type: string
          example: fc0a81d0
        referenceName:
          description: The reference on which this variant occurs. (e.g. `chr_20` or `X`)
          type: string
          example: chr_20
        referenceBases:
          description: The reference bases for this variant. They start at the given start position.
          type: string
          example: TAGGATTGAGCTCTATAT
        referenceSetDbId:
          description: The unique identifier for a ReferenceSet
          type: string
          example: c1ecfef1
        referenceSetName:
          description: The human readable name of the ReferenceSet
          type: string
          example: The Best Assembly Ever
        start:
          description: |-
            This field is optional and may be ignored if there is no relevant map or reference to be associated with.
          
            The start position at which this variant occurs (0-based). This corresponds to the first base of the string 
            of reference bases. Genomic positions are non-negative integers less than reference length. Variants spanning 
            the join of circular genomes are represented as two variants one on each side of the join (position 0).
          type: integer
          example: 500
        svlen:
          description: Length of the - if labeled as such in variant_type - structural variation. Based on the use in VCF v4.2
          type: integer
          example: 1500
        updated:
          description: The time at which this variant was last updated.
          type: string
          format: date-time
        variantSetDbId: 
          description: An array of `VariantSet` IDs this variant belongs to. This also defines the `ReferenceSet` against which the `Variant` is to be interpreted.
          type: array
          items: 
            type: string
          example: ['c8ae400b', 'ef2c204b']
        variantType:
          description: |-
            The "variant_type" is used to denote e.g. structural variants.
            Examples:
              DUP  : duplication of sequence following "start"
              DEL  : deletion of sequence following "start"
          type: string
          example: DUP
