info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths: {}
components:
  schemas:
    Ontology:
      allOf:
      - $ref: '#/components/schemas/OntologyNewRequest'
      - type: object
        properties:
          ontologyDbId:
            description: Ontology database unique identifier
            type: string
            example: 18e186cd

