info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths: {}
components:
  schemas:
    Ontology:
      allOf:
      - $ref: '#/components/schemas/OntologyNewRequest'
      - type: object
        x-brapi-metadata:
          primaryModel: true
          module: BrAPI-Phenotyping
          title: Ontology
          description: The identifier and metadata needed to reference an external controlled vocabulary 
        required:
        - ontologyDbId
        properties:
          ontologyDbId:
            description: Ontology database unique identifier
            type: string
            example: 18e186cd

