info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths:
  /delete/images:
    post:
      summary: Submit a delete request for `Images`
      description: |-
        Submit a delete request for `Images`
      parameters:
      - $ref: '#/components/parameters/authorizationHeader'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ImageSearchRequest'
      responses:
        '200':
          $ref: '#/components/responses/ImageDeleteResponse'
        '400':
          $ref: '#/components/responses/400BadRequest'
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '403':
          $ref: '#/components/responses/403Forbidden'
      tags:
      - Images

components:
  responses:
    ImageDeleteResponse:
      content:
        application/json:
          schema:
            title: ImageDeleteResponse
            type: object
            properties:
              '@context':
                $ref: '#/components/schemas/Context'
              metadata:
                $ref: '#/components/schemas/metadata'
              result:
                properties:
                  imageDbIds:
                    description: The unique ids of the Image records which have been successfully deleted
                    items:
                      type: string
                    type: array
                    example: ['6a4a59d8', '3ff067e0']
                required:
                - imageDbIds
                type: object
            required:
            - metadata
            - result
      description: OK
      headers: {}