components: 
  securitySchemes:
    AuthorizationToken:
      bearerFormat: nonce token or JWT
      description: OAuth Bearer Token - A valid Bearer token to prove authorization
      scheme: bearer
      type: http
info:
  description: BrAPI-HighDemensionality
  title: BrAPI-HighDemensionality
  version: '0.0.0-proposal'
openapi: 3.0.0
paths: {}
security:
- AuthorizationToken: []
servers:
- url: https://test-server.brapi.org/brapi/v2
tags:
- name: NIRS
  description: description
  externalDocs:
    description: description
    url: https://wiki.brapi.org/
