info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths: {}
components:
  schemas:

    DenoiseResponse:
      type: object
      required:
      - cropped_image_id
      - cropped_image_url
      - cropped_image_fullpath
      properties:

        denoised_image_id: 
          type: integer 
          description: The database identifier for the denoised image. 
          example: 703 

        denoised_image_url: 
          type: string 
          description: URL for downloading the denoised image. 
          example: 'https://imagebreed.org/dl/image/703' 

        denoised_image_fullpath: 
          type: string 
          description: File path for denoised image on the server. 
          example: '/export/images/image703' 



