info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths:
  /seasons:
    get:
      summary: Get the Seasons
      description: |-
        Call to retrieve all seasons in the database.
        
        A season is made of 2 parts; the primary year and a term which defines a segment of the year. 
        This could be a traditional season, like "Spring" or "Summer" or this could be a month, like 
        "May" or "June" or this could be an arbitrary season name which is meaningful to the breeding 
        program like "PlantingTime_3" or "Season E"
      parameters:
      - description: The unique identifier for a season. For backward compatibility it can be a string like '2012', '1957-2004'
        example: b230a1d2, Spring_2017, 3
        in: query
        name: seasonDbId
        required: false
        schema:
          type: string
      - description: The term to describe a given season. Example "Spring" OR "May" OR "Planting_Time_7".
        example: Spring
        in: query
        name: season
        required: false
        schema:
          type: string
      - description: The term to describe a given season. Example "Spring" OR "May" OR "Planting_Time_7".
        example: Spring
        in: query
        name: seasonName
        required: false
        schema:
          type: string
      - description: The 4 digit year of a season. Example "2017"
        example: 2017
        in: query
        name: year
        required: false
        schema:
          type: integer
      - $ref: '#/components/parameters/page'
      - $ref: '#/components/parameters/pageSize'
      - $ref: '#/components/parameters/authorizationHeader'
      responses:
        '200':
          $ref: '#/components/responses/SeasonListResponse'
        '400':
          $ref: '#/components/responses/400BadRequest'
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '403':
          $ref: '#/components/responses/403Forbidden'
      tags:
      - Seasons
    post:
      summary: POST new Seasons
      description: Add new season entries to the database
      parameters:
      - $ref: '#/components/parameters/authorizationHeader'
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items: 
                $ref: '#/components/schemas/Season'
      responses:
        '200':
          $ref: '#/components/responses/SeasonListResponse'
        '400':
          $ref: '#/components/responses/400BadRequest'
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '403':
          $ref: '#/components/responses/403Forbidden'
      tags:
      - Seasons      
components:
  responses:
    SeasonListResponse:
      content:
        application/json:
          schema:
            title: SeasonListResponse
            type: object
            required:
            - metadata
            - result
            properties:
              '@context':
                $ref: '#/components/schemas/Context'
              metadata:
                $ref: '#/components/schemas/metadata'
              result:
                type: object
                required:
                - data
                properties:
                  data:
                    description: The `data` array is part of the BrAPI standard List Response JSON container. `data` will always contain the primary list of objects being returned by a BrAPI endpoint. `data` is also the only array impacted by the `metadata.pagination` details. When the pagination parameters change, the `data` array will reflect those changes in the JSON response.
                    items:
                      $ref: '#/components/schemas/Season'
                    type: array
      description: OK
      headers: {}
