info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths:
  /crosses:
    get:
      summary: Get a filtered list of Cross entities
      description: Get a filtered list of Cross entities. 
      parameters:
      - name: crossingProjectDbId 
        description: Search for Crossing Projects with this unique id
        in: query
        required: false
        schema:
          type: string
      - name: crossingProjectName 
        description: The human readable name for a crossing project
        in: query
        required: false
        schema:
          type: string
      - name: crossDbId 
        description: Search for Cross with this unique id
        in: query
        required: false
        schema:
          type: string
      - name: crossName
        description: Search for Cross with this human readable name
        in: query
        required: false
        schema:
          type: string
      - $ref: '#/components/parameters/commonCropName'
      - $ref: '#/components/parameters/programDbId'
      - $ref: '#/components/parameters/externalReferenceID'
      - $ref: '#/components/parameters/externalReferenceId'
      - $ref: '#/components/parameters/externalReferenceSource'
      - $ref: '#/components/parameters/page'
      - $ref: '#/components/parameters/pageSize'
      - $ref: '#/components/parameters/authorizationHeader'
      responses:
        '200':
          $ref: '#/components/responses/CrossesListResponse'
        '400':
          $ref: '#/components/responses/400BadRequest'
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '403':
          $ref: '#/components/responses/403Forbidden'
      tags:
      - Crosses
    post:
      summary: Create new Cross entities on this server
      description: Create new Cross entities on this server
      parameters:
      - $ref: '#/components/parameters/authorizationHeader'
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items: 
                $ref: '#/components/schemas/CrossNewRequest'
      responses:
        '200':
          $ref: '#/components/responses/CrossesListResponse'
        '400':
          $ref: '#/components/responses/400BadRequest'
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '403':
          $ref: '#/components/responses/403Forbidden'
      tags:
      - Crosses
    put:
      summary: Update existing Cross entities on this server
      description: Update existing Cross entities on this server
      parameters:
      - $ref: '#/components/parameters/authorizationHeader'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              description: A map of new Cross entities. The key is the crossDbId of the entity to be updated, the value is the Cross object.
              additionalProperties:
                $ref: '#/components/schemas/CrossNewRequest'
              example:
                '<crossDbId_1>':
                  additionalInfo: {}
                  crossAttributes: 
                  - crossAttributeName: string
                    crossAttributeValue: string
                  crossName: my_Crosses_2018_01
                  crossType: BIPARENTAL
                  crossingProjectDbId: 696d7c92
                  crossingProjectName: my_Crosses_2018
                  parent1: 
                    germplasmDbId: d34b10c3
                    germplasmName: TME_419
                    observationUnitDbId: 3f0a1798
                    observationUnitName: my_Plot_9001
                    parentType: FEMALE
                  parent2: 
                    germplasmDbId: 776a609c
                    germplasmName: TME_419
                    observationUnitDbId: 2e1926a7
                    observationUnitName: my_Plot_9002
                    parentType: MALE
                  pollinationTimeStamp: '2019-08-15T18:49:00.327Z'
                '<crossDbId_2>':
                  additionalInfo: {}
                  crossAttributes: 
                  - crossAttributeName: string
                    crossAttributeValue: string
                  crossName: my_Crosses_2018_02
                  crossType: BIPARENTAL
                  crossingProjectDbId: 696d7c92
                  crossingProjectName: my_Crosses_2018
                  parent1: 
                    germplasmDbId: c43a2fd2
                    germplasmName: TME_419
                    observationUnitDbId: 3f2a37b8
                    observationUnitName: my_Plot_9013
                    parentType: FEMALE
                  parent2: 
                    germplasmDbId: 124b10ad
                    germplasmName: TME_419
                    observationUnitDbId: 27194637
                    observationUnitName: my_Plot_9014
                    parentType: MALE
                  pollinationTimeStamp: '2019-08-15T18:49:00.327Z'
      responses:
        '200':
          $ref: '#/components/responses/CrossesListResponse'
        '400':
          $ref: '#/components/responses/400BadRequest'
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '403':
          $ref: '#/components/responses/403Forbidden'
      tags:
      - Crosses
components:
  responses:
    CrossesListResponse:
      content:
        application/json:
          schema:
            title: CrossesListResponse
            properties:
              '@context':
                $ref: '#/components/schemas/Context'
              metadata:
                $ref: '#/components/schemas/metadata'
              result:
                properties:
                  data:
                    description: The `data` array is part of the BrAPI standard List Response JSON container. `data` will always contain the primary list of objects being returned by a BrAPI endpoint. `data` is also the only array impacted by the `metadata.pagination` details. When the pagination parameters change, the `data` array will reflect those changes in the JSON response.
                    items:
                      $ref: '#/components/schemas/Cross'
                    type: array
                required:
                - data
                type: object
            required:
            - metadata
            - result
            type: object
      description: OK
      headers: {}
    