components: 
  securitySchemes:
    AuthorizationToken:
      bearerFormat: nonce token or JWT
      description: OAuth Bearer Token - A valid Bearer token to prove authorization
      scheme: bearer
      type: http
info:
  description: Imagebreed API
  title: Imagebreed API
  version: '0.1'
openapi: 3.0.0
paths: {}
security:
- AuthorizationToken: []
tags:
- name: Images
  description: Images
  externalDocs:
    description: Docs
    url: https://brapi.org/
- name: Image Collections
  description: Images Collections
  externalDocs:
    description: Docs
    url: https://brapi.org/
- name: Imaging Events
  description: Imaging Events
  externalDocs:
    description: Docs
    url: https://brapi.org/
- name: Image Mutations
  description: Images Mutations
  externalDocs:
    description: Docs
    url: https://brapi.org/
- name: Drone Imagery
  description: Original ImageBase API
  externalDocs:
    description: Docs
    url: https://brapi.org/
