info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths: {}
components:
  schemas:
    PlateNewRequest:
      type: object
      properties:
        additionalInfo:
          additionalProperties:
            type: string
          description: Additional arbitrary info
          type: object
        plateName:
          description: A human readable name for a plate
          type: string
          example: Plate_123_XYZ
        plateBarcode:
          description: A unique identifier physically attached to the plate
          type: string
          example: '11223344'
        sampleType:
          description: The type of samples taken. ex. 'DNA', 'RNA', 'Tissue', etc
          type: string
          enum:
          - DNA
          - RNA
          - TISSUE
          - MIXED
          example: TISSUE
        studyDbId:
          description: The ID which uniquely identifies a study within the given database server
          type: string
          example: 64bd6bf9
        trialDbId: 
          description: The ID which uniquely identifies a trial within the given database server
          type: string
          example: d34c5349
        programDbId: 
          description: The ID which uniquely identifies a program within the given database server
          type: string
          example: bd748e00
        plateFormat:
          $ref: '#/components/schemas/PlateFormat'
        externalReferences: 
          $ref: '#/components/schemas/ExternalReferences'
          

