info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths: {}
components:
  schemas:
    PlateNewRequest:
      type: object
      required:
      - plateName
      properties:
        additionalInfo:
          additionalProperties:
            type: string
          description: A free space containing any additional information related to a particular object. A data source may provide any JSON object, unrestricted by the BrAPI specification.
          type: object
        plateName:
          description: A human readable name for a `Plate`
          type: string
          example: Plate_123_XYZ
        plateBarcode:
          description: A unique identifier physically attached to a `Plate`
          type: string
          example: '11223344'
        sampleType:
          description: The type of samples taken. ex. 'DNA', 'RNA', 'Tissue', etc
          type: string
          enum:
          - DNA
          - RNA
          - TISSUE
          - MIXED
          example: TISSUE
        studyDbId:
          description: The ID which uniquely identifies a `Study` within the given database server
          type: string
          example: 64bd6bf9
        trialDbId: 
          description: The ID which uniquely identifies a `Trial` within the given database server
          type: string
          example: d34c5349
        programDbId: 
          description: The ID which uniquely identifies a `Program` within the given database server
          type: string
          example: bd748e00
        plateFormat:
          $ref: '#/components/schemas/PlateFormat'
        externalReferences: 
          $ref: '#/components/schemas/ExternalReferences'
          

