info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths:
  /calls:
    get:
      summary: Gets a filtered list of `Calls`
      description: |-
        Gets a filtered list of `Call` JSON objects.
        
        ** THIS ENDPOINT USES TOKEN BASED PAGING **
      parameters:
        - name: callSetDbId
          description: The ID of the `CallSet` to be retrieved.
          in: query
          required: false
          schema:
            type: string
        - name: variantDbId
          description: The ID of the `Variant` to be retrieved.
          in: query
          required: false
          schema:
            type: string
        - name: variantSetDbId
          description: The ID of the `VariantSet` to be retrieved.
          in: query
          required: false
          schema:
            type: string
        - name: expandHomozygotes
          description: Should homozygotes be expanded (true) or collapsed into a single occurrence (false)
          in: query
          required: false
          schema:
            type: boolean
        - name: unknownString
          description: The string to use as a representation for missing data
          in: query
          required: false
          schema:
            type: string
        - name: sepPhased
          description: The string to use as a separator for phased allele calls
          in: query
          required: false
          schema:
            type: string
        - name: sepUnphased
          description: The string to use as a separator for unphased allele calls
          in: query
          required: false
          schema:
            type: string
        - $ref: '#/components/parameters/pageToken'
        - $ref: '#/components/parameters/pageSize'
        - $ref: '#/components/parameters/authorizationHeader'
      responses:
        '200':
          $ref: '#/components/responses/CallsListResponse'
        '400':
          $ref: '#/components/responses/400BadRequest'
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '403':
          $ref: '#/components/responses/403Forbidden'
      tags:
        - Calls