info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths:
  /search/variantmatrix:
    post:
      summary: Submit a search request for `Calls`
      description: |-
        Submit a search request for `Calls`<br/>
        Search requests allow a client to send a complex query for data. However, the server may not respond with the search results immediately. 
        If a server needs more time to process the request, it might respond with a `searchResultsDbId`. 
        Use the corresponding `GET /search/calls/{searchResultsDbId}` to retrieve the results of the search. <br/> 
        Review the <a target="_blank" href="https://wiki.brapi.org/index.php/Search_Services#POST_Search_Entity">Search Services documentation</a> for additional implementation details. 
        <br/>
      parameters:
      - $ref: '#/components/parameters/authorizationHeader'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CallsSearchRequest'
        description: Study Search request
      responses:
        '200':
          $ref: '#/components/responses/VariantMatrixResponse'
        '202':
          $ref: '#/components/responses/202AcceptedSearchResponse'
        '400':
          $ref: '#/components/responses/400BadRequest'
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '403':
          $ref: '#/components/responses/403Forbidden'
      tags:
      - Genotype-Matrix-Redesign