info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths:
  /variantmatrix3:
    get:
      summary: Two dimensional matrix representing the raw contents of a VCF
      description: |-
        Two dimensional matrix representing the raw contents of a VCF
      parameters:
        - $ref: '#/components/parameters/germplasmDbId'
        - $ref: '#/components/parameters/germplasmName'
        - $ref: '#/components/parameters/germplasmPUI'
        - $ref: '#/components/parameters/callSetDbId'
        - $ref: '#/components/parameters/variantDbId'
        - $ref: '#/components/parameters/variantSetDbId'
        - $ref: '#/components/parameters/expandHomozygotes'
        - $ref: '#/components/parameters/unknownString'
        - $ref: '#/components/parameters/sepPhased'
        - $ref: '#/components/parameters/sepUnphased'
        - $ref: '#/components/parameters/pageToken'
        - $ref: '#/components/parameters/pageSize'
        - $ref: '#/components/parameters/authorizationHeader'
      responses:
        '200':
          $ref: '#/components/responses/MatrixResponse_3'
        '400':
          $ref: '#/components/responses/400BadRequest'
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '403':
          $ref: '#/components/responses/403Forbidden'
      tags:
        - Genotype-Matrix-Redesign

components:
  responses:
    MatrixResponse_3: 
      description: OK
      headers: {}
      content:
        application/json:
          schema:
            title: MatrixResponse_3
            required:
            - metadata
            - result
            type: object
            properties:
              '@context':
                $ref: '#/components/schemas/Context'
              metadata:
                $ref: '#/components/schemas/metadata'
              result:
                type: object
                required:
                - data
                properties:
                  callSetDbIds:
                    type: array
                    items:
                      type: string
                    example: ['aca00001', 'aca00002', 'aca00003']
                  variantDbIds:
                    type: array
                    items:
                      type: string
                    example: ['feb54257', 'feb40355', 'feb40323']
                  data:
                    type: array
                    items:
                      type: array
                      items:
                        type: string
                    example:
                    - ['0|0', '1|0', '1/1']
                    - ['0|0', '1|0', '1/1']
                    - ['0|0', '1|0', '1/1']
                  dataMasks:
                    type: array
                    items:
                      type: object
                      properties:
                        maskType:
                          type: string
                          enum:
                          - Genotype Quality
                          - Read Depth
                          - Haplotype Quality
                          example: Genotype Quality
                        mask:
                          type: array
                          items:
                            type: array
                            items:
                              type: string
                          example:
                          - ['48', '48', '43']
                          - ['49', '3', '41']
                          - ['21', '2', '35']
                  expandHomozygotes: 
                    description: Should homozygotes be expanded (true) or collapsed into a single occurrence (false)
                    type: boolean
                    example: true
                  sepPhased:
                    description: The string used as a separator for phased allele calls.
                    type: string
                    example: '|'
                  sepUnphased:
                    description: The string used as a separator for unphased allele calls.
                    type: string
                    example: '/'
                  unknownString:
                    description: The string used as a representation for missing data.
                    type: string
                    example: '.'