info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths:
  /variantmatrix:
    get:
      summary: Two dimensional matrix representing the raw contents of a VCF
      description: |-
        Two dimensional matrix representing the raw contents of a VCF
      parameters:
        - name: dimensionVariantPage
          description: The requested page number for the Variant dimension of the matrix
          in: query
          required: false
          schema:
            type: string
        - name: dimensionVariantPage
          description: The requested page size for the Variant dimension of the matrix
          in: query
          required: false
          schema:
            type: string
        - name: dimensionVariantPage
          description: The requested page number for the CallSet dimension of the matrix
          in: query
          required: false
          schema:
            type: string
        - name: dimensionVariantPage
          description: The requested page size for the CallSet dimension of the matrix
          in: query
          required: false
          schema:
            type: string
        - $ref: '#/components/parameters/positionRange'
        - $ref: '#/components/parameters/germplasmDbId'
        - $ref: '#/components/parameters/germplasmName'
        - $ref: '#/components/parameters/germplasmPUI'
        - $ref: '#/components/parameters/callSetDbId'
        - $ref: '#/components/parameters/variantDbId'
        - $ref: '#/components/parameters/variantSetDbId'
        - $ref: '#/components/parameters/expandHomozygotes'
        - $ref: '#/components/parameters/unknownString'
        - $ref: '#/components/parameters/sepPhased'
        - $ref: '#/components/parameters/sepUnphased'
        - $ref: '#/components/parameters/authorizationHeader'
      responses:
        '200':
          $ref: '#/components/responses/VariantMatrixResponse'
        '400':
          $ref: '#/components/responses/400BadRequest'
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '403':
          $ref: '#/components/responses/403Forbidden'
      tags:
        - Genotype-Matrix-Redesign

components:
  responses:
    VariantMatrixResponse: 
      description: OK
      headers: {}
      content:
        application/json:
          schema:
            title: VariantMatrixResponse
            required:
            - metadata
            - result
            type: object
            properties:
              '@context':
                $ref: '#/components/schemas/Context'
              metadata:
                $ref: '#/components/schemas/metadata'
              result:
                $ref: '#/components/schemas/VariantMatrix'
