info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths:
  /variantmatrix2:
    get:
      summary: Two dimensional matrix representing the raw contents of a VCF
      description: |-
        Two dimensional matrix representing the raw contents of a VCF
      parameters:
        - $ref: '#/components/parameters/callSetDbId'
        - $ref: '#/components/parameters/variantDbId'
        - $ref: '#/components/parameters/variantSetDbId'
        - $ref: '#/components/parameters/expandHomozygotes'
        - $ref: '#/components/parameters/unknownString'
        - $ref: '#/components/parameters/sepPhased'
        - $ref: '#/components/parameters/sepUnphased'
        - $ref: '#/components/parameters/pageToken'
        - $ref: '#/components/parameters/pageSize'
        - $ref: '#/components/parameters/authorizationHeader'
      responses:
        '200':
          $ref: '#/components/responses/MatrixResponse_2'
        '400':
          $ref: '#/components/responses/400BadRequest'
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '403':
          $ref: '#/components/responses/403Forbidden'
      tags:
        - Genotype-Matrix-Redesign

components:
  responses:
    MatrixResponse_2: 
      description: OK
      headers: {}
      content:
        application/json:
          schema:
            title: MatrixResponse_2
            required:
            - metadata
            - result
            type: object
            properties:
              '@context':
                $ref: '#/components/schemas/Context'
              metadata:
                $ref: '#/components/schemas/metadata'
              result:
                type: object
                required:
                - data
                properties:
                  format:
                    type: string
                    example: GT:GQ:DP:HQ
                  callSetDbIds:
                    type: array
                    items:
                      type: string
                    example: ['aca00001', 'aca00002', 'aca00003']
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        variantDbId: 
                          type: string
                          example: feb54257 
                        row:
                          type: array
                          items:
                            type: string
                    example:
                    - variantDbId: feb54257 
                      row: ['0|0:48:1:51,51', '1|0:48:8:51,51', '1/1:43:5:.,.']
                    - variantDbId: feb040355 
                      row: ['0|0:48:1:51,51', '1|0:48:8:51,51', '1/1:43:5:.,.']
                    - variantDbId: feb40323 
                      row: ['0|0:48:1:51,51', '1|0:48:8:51,51', '1/1:43:5:.,.']
                  expandHomozygotes: 
                    description: Should homozygotes be expanded (true) or collapsed into a single occurrence (false)
                    type: boolean
                    example: true
                  sepPhased:
                    description: The string used as a separator for phased allele calls.
                    type: string
                    example: '~'
                  sepUnphased:
                    description: The string used as a separator for unphased allele calls.
                    type: string
                    example: '|'
                  unknownString:
                    description: The string used as a representation for missing data.
                    type: string
                    example: '-'