info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths:
  /variantmatrix1:
    get:
      summary: Two dimensional matrix representing the raw contents of a VCF
      description: |-
        Two dimensional matrix representing the raw contents of a VCF
      parameters:
        - $ref: '#/components/parameters/callSetDbId'
        - $ref: '#/components/parameters/variantDbId'
        - $ref: '#/components/parameters/variantSetDbId'
        - $ref: '#/components/parameters/expandHomozygotes'
        - $ref: '#/components/parameters/unknownString'
        - $ref: '#/components/parameters/sepPhased'
        - $ref: '#/components/parameters/sepUnphased'
        - $ref: '#/components/parameters/pageToken'
        - $ref: '#/components/parameters/pageSize'
        - $ref: '#/components/parameters/authorizationHeader'
      responses:
        '200':
          $ref: '#/components/responses/MatrixResponse_1'
        '400':
          $ref: '#/components/responses/400BadRequest'
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '403':
          $ref: '#/components/responses/403Forbidden'
      tags:
        - Genotype-Matrix-Redesign

components:
  responses:
    MatrixResponse_1: 
      description: OK
      headers: {}
      content:
        application/json:
          schema:
            title: MatrixResponse_1
            required:
            - metadata
            - result
            type: object
            properties:
              '@context':
                $ref: '#/components/schemas/Context'
              metadata:
                $ref: '#/components/schemas/metadata'
              result:
                type: object
                required:
                - data
                properties:
                  data:
                    type: array
                    items:
                      type: array
                      items: 
                        type: string
                    example:
                    - - '#CHROM'
                      - 'POS'
                      - 'ID'
                      - 'REF'
                      - 'ALT'
                      - 'QUAL'
                      - 'FILTER'
                      - 'INFO'
                      - 'FORMAT'
                      - 'aca00001'
                      - 'aca00002'
                      - 'aca00003'
                    - - '20'
                      - '14370'
                      - 'feb54257'
                      - 'G'
                      - 'A'
                      - '29'
                      - 'PASS'
                      - 'NS=3;DP=14;AF=0.5;DB;H2'
                      - 'GT:GQ:DP:HQ'
                      - '0|0:48:1:51,51'
                      - '1|0:48:8:51,51'
                      - '1/1:43:5:.,.'
                    - - '20'
                      - '17330'
                      - 'feb40323'
                      - 'T'
                      - 'A'
                      - '3'
                      - 'q10'
                      - 'NS=3;DP=11;AF=0.017'
                      - 'GT:GQ:DP:HQ'
                      - '0|0:49:3:58,50'
                      - '0|1:3:5:65,3'
                      - '0/0:41:3'
                    - - '20'
                      - '1110696'
                      - 'feb40355'
                      - 'A'
                      - 'G,T'
                      - '67'
                      - 'PASS'
                      - 'NS=2;DP=10;AF=0.333,0.667;AA=T;DB'
                      - 'GT:GQ:DP:HQ'
                      - '1|2:21:6:23,27'
                      - '2|1:2:0:18,2'
                      - '2/2:35:4'
                  vcfHeaders:
                    type: array
                    items:
                      type: string
                    example:
                    - ##fileformat=VCFv4.2
                    - ##fileDate=20090805
                    - ##source=myImputationProgramV3.1
                    - ##reference=file:///seq/references/1000GenomesPilot-NCBI36.fasta
                    - ##contig=<ID=20,length=62435964,assembly=B36,md5=f126cdf8a6e0c7f379d618ff66beb2da,species="Homo sapiens",taxonomy=x>
                    - ##phasing=partial
                    - ##INFO=<ID=NS,Number=1,Type=Integer,Description="Number of Samples With Data">
                    - ##INFO=<ID=DP,Number=1,Type=Integer,Description="Total Depth">
                    - ##INFO=<ID=AF,Number=A,Type=Float,Description="Allele Frequency">
                    - ##INFO=<ID=AA,Number=1,Type=String,Description="Ancestral Allele">
                    - ##INFO=<ID=DB,Number=0,Type=Flag,Description="dbSNP membership, build 129">
                    - ##INFO=<ID=H2,Number=0,Type=Flag,Description="HapMap2 membership">
                    - ##FILTER=<ID=q10,Description="Quality below 10">
                    - ##FILTER=<ID=s50,Description="Less than 50% of samples have data">
                    - ##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
                    - ##FORMAT=<ID=GQ,Number=1,Type=Integer,Description="Genotype Quality">
                    - ##FORMAT=<ID=DP,Number=1,Type=Integer,Description="Read Depth">
                    - ##FORMAT=<ID=HQ,Number=2,Type=Integer,Description="Haplotype Quality">
                  expandHomozygotes: 
                    description: Should homozygotes be expanded (true) or collapsed into a single occurrence (false)
                    type: boolean
                    example: true
                  sepPhased:
                    description: The string used as a separator for phased allele calls.
                    type: string
                    example: '~'
                  sepUnphased:
                    description: The string used as a separator for unphased allele calls.
                    type: string
                    example: '|'
                  unknownString:
                    description: The string used as a representation for missing data.
                    type: string
                    example: '-'