info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths:
  /programs:
    get:
      summary: Get a filtered list of breeding Programs
      description: Get a filtered list of breeding Programs. This list can be filtered by common crop name to narrow results to a specific crop.
      parameters:
      - name: abbreviation
        description: A shortened version of the human readable name for a Program
        in: query
        required: false
        schema:
          type: string
      - name: programType
        description: |-
            The type of program entity this object represents
            <br/> 'STANARD' represents a standard, permenant breeding program
            <br/> 'PROJECT' represents a short term project, usually with a set time limit based on funding 
        in: query
        required: false
        schema:
          type: string
          enum:
          - STANARD
          - PROJECT
      - $ref: '#/components/parameters/commonCropName'
      - $ref: '#/components/parameters/programDbId'
      - $ref: '#/components/parameters/programName'
      - $ref: '#/components/parameters/externalReferenceID' 
      - $ref: '#/components/parameters/externalReferenceId'
      - $ref: '#/components/parameters/externalReferenceSource'
      - $ref: '#/components/parameters/page'
      - $ref: '#/components/parameters/pageSize'
      - $ref: '#/components/parameters/authorizationHeader'
      responses:
        '200':
          $ref: '#/components/responses/ProgramListResponse'
        '400':
          $ref: '#/components/responses/400BadRequest'
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '403':
          $ref: '#/components/responses/403Forbidden'
      tags:
      - Programs
    post:
      summary: Add new breeding Programs to the database
      description: Add new breeding Programs to the database. The `programDbId` is set by the server, all other fields are take from the request body, or a default value is used.
      parameters:
      - $ref: '#/components/parameters/authorizationHeader'
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items: 
                $ref: '#/components/schemas/ProgramNewRequest'
      responses:
        '200':
          $ref: '#/components/responses/ProgramListResponse'
        '400':
          $ref: '#/components/responses/400BadRequest'
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '403':
          $ref: '#/components/responses/403Forbidden'
      tags:
      - Programs
components:
  responses:
    ProgramListResponse:
      content:
        application/json:
          schema:
            title: ProgramListResponse
            properties:
              '@context':
                $ref: '#/components/schemas/Context'
              metadata:
                $ref: '#/components/schemas/metadata'
              result:
                properties:
                  data:
                    description: The `data` array is part of the BrAPI standard List Response JSON container. `data` will always contain the primary list of objects being returned by a BrAPI endpoint. `data` is also the only array impacted by the `metadata.pagination` details. When the pagination parameters change, the `data` array will reflect those changes in the JSON response.
                    items:
                      $ref: '#/components/schemas/Program'
                    type: array
                required:
                - data
                type: object
            required:
            - metadata
            - result
            type: object
      description: OK
      headers: {}
