info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths: {}
components:
  schemas:
    ObservationSearchRequest: 
      allOf:
      - $ref: '#/components/schemas/SearchRequestParametersPaging'
      - $ref: '#/components/schemas/SearchRequestParametersCommonCropNames'
      - $ref: '#/components/schemas/SearchRequestParametersPrograms'
      - $ref: '#/components/schemas/SearchRequestParametersTrials'
      - $ref: '#/components/schemas/SearchRequestParametersStudies'
      - $ref: '#/components/schemas/SearchRequestParametersGermplasm'
      - $ref: '#/components/schemas/SearchRequestParametersLocations'
      - $ref: '#/components/schemas/SearchRequestParametersObservationVariables'
      - $ref: '#/components/schemas/SearchRequestParametersExternalReferences'
      - type: object
        properties:
          observationDbIds:
            description: The unique id of an Observation
            items:
              type: string
            type: array
            example: ['6a4a59d8', '3ff067e0']
          observationUnitDbIds: 
            description: The unique id of an Observation Unit
            items:
              type: string
            type: array
            example: ['76f559b5', '066bc5d3'] 
          observationLevels: 
            description: Searches for values in ObservationUnit->observationUnitPosition->observationLevel
            type: array 
            items:
              $ref: '#/components/schemas/ObservationUnitLevel' 
            example:
              - levelName: plot
                levelCode: Plot_123
              - levelName: plot
                levelCode: Plot_456
              - levelName: plot
                levelCode: Plot_789
          observationLevelRelationships: 
            description: Searches for values in ObservationUnit->observationUnitPosition->observationLevelRelationships
            type: array 
            items: 
              $ref: '#/components/schemas/ObservationUnitLevelRelationship'
            example: 
              - levelName: field
                levelCode: Field_1
          observationTimeStampRangeEnd:
            description: Timestamp range end
            format: date-time
            type: string
          observationTimeStampRangeStart:
            description: Timestamp range start
            format: date-time
            type: string
          seasonDbIds: 
            description: The year or Phenotyping campaign of a multi-annual study (trees, grape, ...)
            items:
              type: string
            type: array
            example: ['Spring 2018', 'Season A']
  
