info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths: {}
components:
  schemas:
    Observation:
      allOf:
      - $ref: '#/components/schemas/ObservationNewRequest'
      - type: object
        x-brapi-metadata:
          primaryModel: true
          module: BrAPI-Phenotyping
          title: Observation
          description: A value assigned for a specific ObservationVariable when observing a specific ObservationUnit. 
        required:
        - observationDbId
        properties:
          observationDbId:
            description: The ID which uniquely identifies an observation
            type: string
            example: ef24b615

