info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths:
  /studies:
    get:
      summary: Get a filtered list of Studies
      description: |-
        Get list of studies
        
        StartDate and endDate should be ISO-8601 format for dates
      parameters:
      - description: Filter based on study type unique identifier
        in: query
        name: studyType
        required: false
        schema:
          type: string
      - description: Filter by location
        in: query
        name: locationDbId
        required: false
        schema:
          type: string
      - description: Filter by season or year
        in: query
        name: seasonDbId
        required: false
        schema:
          type: string
      - description: Filter by trial
        in: query
        name: trialDbId
        required: false
        schema:
          type: string
      - description: Filter by study DbId
        in: query
        name: studyDbId
        required: false
        schema:
          type: string
      - description: Filter by study name
        in: query
        name: studyName
        required: false
        schema:
          type: string
      - description: Filter by study code
        in: query
        name: studyCode
        required: false
        schema:
          type: string
      - description: Filter by study PUI
        in: query
        name: studyPUI
        required: false
        schema:
          type: string
      - description: Filter by germplasm DbId
        in: query
        name: germplasmDbId
        required: false
        schema:
          type: string
      - description: Filter by observation variable DbId
        in: query
        name: observationVariableDbId
        required: false
        schema:
          type: string
      - description: Filter active status true/false.
        in: query
        name: active
        required: false
        schema:
          type: boolean
      - description: Name of the field to sort by.
        in: query
        name: sortBy
        required: false
        schema:
          enum:
          - studyDbId
          - trialDbId
          - programDbId
          - locationDbId
          - seasonDbId
          - studyType
          - studyName
          - studyLocation
          - programName
          type: string
      - description: Sort order direction. Ascending/Descending.
        in: query
        name: sortOrder
        required: false
        schema:
          enum:
          - asc
          - ASC
          - desc
          - DESC
          type: string
      - $ref: '#/components/parameters/commonCropName'
      - $ref: '#/components/parameters/programDbId'
      - $ref: '#/components/parameters/externalReferenceID' 
      - $ref: '#/components/parameters/externalReferenceId'
      - $ref: '#/components/parameters/externalReferenceSource'
      - $ref: '#/components/parameters/page'
      - $ref: '#/components/parameters/pageSize'
      - $ref: '#/components/parameters/authorizationHeader'
      responses:
        '200':
          $ref: '#/components/responses/StudyListResponse'
        '400':
          $ref: '#/components/responses/400BadRequest'
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '403':
          $ref: '#/components/responses/403Forbidden'
      tags:
      - Studies
    post:
      summary: Create new Studies. 
      description: |-
        Create new studies
        
        Implementation Notes
        
        StartDate and endDate should be ISO-8601 format for dates
        
        `studDbId` is generated by the server.
      parameters:
      - $ref: '#/components/parameters/authorizationHeader'
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items: 
                $ref: '#/components/schemas/StudyNewRequest'
      responses:
        '200':
          $ref: '#/components/responses/StudyListResponse'
        '400':
          $ref: '#/components/responses/400BadRequest'
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '403':
          $ref: '#/components/responses/403Forbidden'
      tags: 
      - Studies
components:
  responses:
    StudyListResponse:
      content:
        application/json:
          schema:
            title: StudyListResponse
            properties:
              '@context':
                $ref: '#/components/schemas/Context'
              metadata:
                $ref: '#/components/schemas/metadata'
              result:
                properties:
                  data:
                    items:
                      $ref: '#/components/schemas/Study'
                    type: array
                required:
                - data
                type: object
            required:
            - metadata
            - result
            type: object
      description: OK
      headers: {}
      