info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths:
  /plates/{plateDbId}:
    get:
      summary: Get the details of a specific Plate.
      description: Get the details of a specific Plate. Each Plate is a collection of samples that are physically grouped together.
      parameters:
      - description: The ID which uniquely identifies a plate
        in: path
        name: plateDbId
        required: true
        schema:
          type: string
      - $ref: '#/components/parameters/authorizationHeader'
      responses:
        '200':
          $ref: '#/components/responses/PlateSingleResponse'
        '400':
          $ref: '#/components/responses/400BadRequest'
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '403':
          $ref: '#/components/responses/403Forbidden'
        '404':
          $ref: '#/components/responses/404NotFound'
      tags:
      - Plates
components:
  responses:
    PlateSingleResponse:
      content:
        application/json:
          schema:
            title: PlateSingleResponse
            type: object
            properties:
              '@context':
                $ref: '#/components/schemas/Context'
              metadata:
                $ref: '#/components/schemas/metadata'
              result:
                $ref: '#/components/schemas/Plate'
            required:
            - metadata
            - result
      description: OK
      headers: {}
