info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths:
  /samples:
    get:
      summary: Get the Samples
      description: Used to retrieve list of Samples from a Sample Tracking system based on some search criteria.
      parameters:
      - name: sampleDbId
        description: The unique identifier for a `Sample`
        in: query
        required: false
        schema:
          type: string
      - name: sampleName
        description: The human readable name of the `Sample`
        in: query
        required: false
        schema:
          type: string
      - name: sampleGroupDbId
        description: The unique identifier for a group of related `Samples`
        in: query
        required: false
        schema:
          type: string
      - name: observationUnitDbId
        description: The ID which uniquely identifies an `ObservationUnit`
        in: query
        required: false
        schema:
          type: string
      - name: plateDbId
        description: The ID which uniquely identifies a `Plate` of `Sample`
        in: query
        required: false
        schema:
          type: string
      - name: plateName
        description: The human readable name of a `Plate` of `Sample`
        in: query
        required: false
        schema:
          type: string
      - $ref: '#/components/parameters/commonCropName'
      - $ref: '#/components/parameters/programDbId'
      - $ref: '#/components/parameters/trialDbId'
      - $ref: '#/components/parameters/studyDbId'
      - $ref: '#/components/parameters/germplasmDbId'
      - $ref: '#/components/parameters/externalReferenceID'
      - $ref: '#/components/parameters/externalReferenceId'
      - $ref: '#/components/parameters/externalReferenceSource'
      - $ref: '#/components/parameters/page'
      - $ref: '#/components/parameters/pageSize'
      - $ref: '#/components/parameters/authorizationHeader'
      responses:
        '200':
          $ref: '#/components/responses/SampleListResponse'
        '400':
          $ref: '#/components/responses/400BadRequest'
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '403':
          $ref: '#/components/responses/403Forbidden'
      tags:
      - Samples
    post:
      summary: Add new Samples
      description: Call to register the event of a sample being taken. Sample ID is assigned as a result of the operation and returned in response.
      parameters:
      - $ref: '#/components/parameters/authorizationHeader'
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/SampleNewRequest'
      responses:
        '200':
          $ref: '#/components/responses/SampleListResponse'
        '400':
          $ref: '#/components/responses/400BadRequest'
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '403':
          $ref: '#/components/responses/403Forbidden'
      tags:
      - Samples
    put:
      summary: Update the details of existing Samples
      description: Update the details of existing Samples
      parameters:
      - $ref: '#/components/parameters/authorizationHeader'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              additionalProperties:
                $ref: '#/components/schemas/SampleNewRequest'
              example:
                '<sampleDbId_1>':
                  additionalInfo: {}
                  column: 6
                  externalReferences: []
                  germplasmDbId: 7e08d538
                  observationUnitDbId: 073a3ce5
                  plateDbId: 2dce16d1
                  plateName: Plate_alpha_20191022
                  programDbId: bd748e00
                  row: B
                  sampleBarcode: 3a027b59
                  sampleDescription: This sample was taken from the root of a tree
                  sampleGroupDbId: 8524b436
                  sampleName: Sample_alpha_20191022
                  samplePUI: doi:10.15454/312953986E3
                  sampleTimestamp: 2018-01-01T18:47:23-0600
                  sampleType: Tissue
                  studyDbId: 64bd6bf9
                  takenBy: Bob
                  tissueType: Root
                  trialDbId: d34c5349
                  well: B6
                '<sampleDbId_2>':
                  additionalInfo: {}
                  column: 6
                  externalReferences: []
                  germplasmDbId: 7e08d538
                  observationUnitDbId: 073a3ce5
                  plateDbId: 2dce16d1
                  plateName: Plate_alpha_20191022
                  programDbId: bd748e00
                  row: B
                  sampleBarcode: 3a027b59
                  sampleDescription: This sample was taken from the root of a tree
                  sampleGroupDbId: 8524b436
                  sampleName: Sample_alpha_20191022
                  samplePUI: doi:10.15454/312953986E3
                  sampleTimestamp: 2018-01-01T18:47:23-0600
                  sampleType: Tissue
                  studyDbId: 64bd6bf9
                  takenBy: Bob
                  tissueType: Root
                  trialDbId: d34c5349
                  well: B6
      responses:
        '200':
          $ref: '#/components/responses/SampleListResponse'
        '400':
          $ref: '#/components/responses/400BadRequest'
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '403':
          $ref: '#/components/responses/403Forbidden'
        '404':
          $ref: '#/components/responses/404NotFound'
      tags:
      - Samples
components:
  responses:
    SampleListResponse:
      content:
        application/json:
          schema:
            title: SampleListResponse
            type: object
            properties:
              '@context':
                $ref: '#/components/schemas/Context'
              metadata:
                $ref: '#/components/schemas/metadata'
              result:
                properties:
                  data:
                    description: The `data` array is part of the BrAPI standard List Response JSON container. `data` will always contain the primary list of objects being returned by a BrAPI endpoint. `data` is also the only array impacted by the `metadata.pagination` details. When the pagination parameters change, the `data` array will reflect those changes in the JSON response.
                    items:
                      $ref: '#/components/schemas/Sample'
                    type: array
                required:
                - data
                type: object
            required:
            - metadata
            - result
      description: OK
      headers: {}
      
