info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths: {}
components:
  schemas:
    SearchRequestParametersStudies: 
      type: object
      properties:
        studyDbIds:
          description: List of study identifiers to search for
          items:
            type: string
          type: array
          example: ['cf6c4bd4', '691e69d6']
        studyNames:
          description: List of study names to filter search results
          items:
            type: string
          type: array
          example: ['The First Bob Study 2017', 'Wheat Yield Trial 246']
