info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths: {}
components:
  schemas:
    SearchRequestParametersPaging: 
      type: object
      properties:
        page:
          description: Which result page is requested. The page indexing starts at 0 (the first page is 'page'= 0). Default is `0`.
          type: integer
          example: 0
        pageSize:
          description: The size of the pages to be returned. Default is `1000`.
          example: 1000
          type: integer
