info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths: {}
components:
  schemas:
    ListValue:
      deprecated: true
      type: object
      description: |-
        **Deprecated in v2.1** Please use `genotypeValue` or `genotypeMetadata`. Github issue number #491             
        <br>`ListValue` is a wrapper around a repeated field of values.
        <br>The JSON representation for `ListValue` is JSON array.
      properties:
        values:
          type: array
          deprecated: true
          description: |-
            **Deprecated in v2.1** Please use `genotypeValue` or `genotypeMetadata`. Github issue number #491             
            <br>Repeated field of dynamically typed values.
          items:
            oneOf:
            - description: Represents a boolean value.
              format: boolean
              type: boolean
            - description: Represents a double value.
              format: double
              type: number
            - description: Represents a string value.
              type: string
          example: [ 'AA' ]
