info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths:
  /observations/table:
    get:
      summary: Get a list of Observations in a table format
      description: |-
        <p>This service is designed to retrieve a table of time dependant observation values as a matrix of Observation Units and Observation Variables.
        This is also sometimes called a Time Series. This service takes the "Sparse Table" approach for representing this time dependant data.</p>
        <p>The table may be represented by JSON, CSV, or TSV. The "Accept" HTTP header is used for the client to request different return formats. 
        By default, if the "Accept" header is not included in the request, the server should return JSON as described below.</p>
        <p>The table is REQUIRED to have the following columns</p>
        <ul>
          <li>observationUnitDbId - Each row is related to one Observation Unit</li>
          <li>observationTimeStamp - Each row is has a time stamp for when the observation was taken</li>
          <li>At least one column with an observationVariableDbId</li>
        </ul>
        <p>The table may have any or all of the following OPTIONAL columns. Included columns are decided by the server developer</p>
        <ul>
          <li>observationUnitName</li>
          <li>studyDbId</li>
          <li>studyName</li>
          <li>germplasmDbId</li>
          <li>germplasmName</li>
          <li>positionCoordinateX</li>
          <li>positionCoordinateY</li>
          <li>year</li>
        </ul>
        <p>The table also may have any number of Observation Unit Hierarchy Level columns. For example:</p>
        <ul>
          <li>field</li>
          <li>plot</li>
          <li>sub-plot</li>
          <li>plant</li>
          <li>pot</li>
          <li>block</li>
          <li>entry</li>
          <li>rep</li>
        </ul>
        <p>The JSON representation provides a pair of extra arrays for defining the headers of the table. 
        The first array "headerRow" will always contain "observationUnitDbId" and any or all of the OPTIONAL column header names. 
        The second array "observationVariables" contains the names and DbIds for the Observation Variables represented in the table. 
        By appending the two arrays, you can construct the complete header row of the table. </p>
        <p>For CSV and TSV representations of the table, an extra header row is needed to describe both the Observation Variable DbId and the Observation Variable Name for each data column. 
        See the example responses below</p> 
      parameters:
      - description: The unique ID of an Observation Unit
        in: query
        name: observationUnitDbId
        required: false
        schema:
          type: string
      - description: The unique ID of an observation variable
        in: query
        name: observationVariableDbId
        required: false
        schema:
          type: string
      - description: The unique ID of a location where these observations were collected
        in: query
        name: locationDbId
        required: false
        schema:
          type: string
      - description: The year or Phenotyping campaign of a multi-annual study (trees, grape, ...)
        in: query
        name: seasonDbId
        required: false
        schema:
          type: string
      - description: |-
          **Deprecated in v2.1** Please use `observationUnitLevelName`. Github issue number #464 
          <br>The type of the observationUnit. Returns only the observation unit of the specified type; the parent levels ID can be accessed through observationUnitStructure. 
        in: query
        name: observationLevel
        required: false
        schema:
          type: string
        deprecated: true
      - description: Permanent unique identifier which references the search results
        in: query
        name: searchResultsDbId
        required: false
        schema:
          type: string
      - description: Timestamp range start
        in: query
        name: observationTimeStampRangeStart
        required: false
        schema:
          format: date-time
          type: string
      - description: Timestamp range end
        in: query
        name: observationTimeStampRangeEnd
        required: false
        schema:
          format: date-time
          type: string
      - $ref: '#/components/parameters/programDbId'
      - $ref: '#/components/parameters/trialDbId'
      - $ref: '#/components/parameters/studyDbId'
      - $ref: '#/components/parameters/germplasmDbId'
      - $ref: '#/components/parameters/observationUnitLevelName'
      - $ref: '#/components/parameters/observationUnitLevelOrder'
      - $ref: '#/components/parameters/observationUnitLevelCode'
      - $ref: '#/components/parameters/observationUnitLevelRelationshipName'
      - $ref: '#/components/parameters/observationUnitLevelRelationshipOrder'
      - $ref: '#/components/parameters/observationUnitLevelRelationshipCode'
      - $ref: '#/components/parameters/observationUnitLevelRelationshipDbId'
      - $ref: '#/components/parameters/acceptHeader'
      - $ref: '#/components/parameters/authorizationHeader'
      responses:
        '200':
          $ref: '#/components/responses/ObservationTableResponse'
        '400':
          $ref: '#/components/responses/400BadRequest'
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '403':
          $ref: '#/components/responses/403Forbidden'
      tags:
      - Observations
components:
  responses:
    ObservationTableResponse:
      content:
        application/json:
          schema:
            title: ObservationTableResponse
            type: object
            properties:
              '@context':
                $ref: '#/components/schemas/Context'
              metadata:
                $ref: '#/components/schemas/metadata'
              result:
                $ref: '#/components/schemas/ObservationTable'
            required:
            - metadata
            - result
        text/csv: 
          example: |-
            "observationUnitDbId","observationUnitName","studyDbId","studyName","germplasmDbId","germplasmName","positionCoordinateX","positionCoordinateY","year","field","plot","sub-plot","plant","pot","block","entry","rep","f959a77d","8341dee0","84c9fd86","93d80c95"
            
            "","","","","","","","","","","","","","","","","","Plant height","Carotenoid","Root color","Virus severity"
                  
            "2019-09-10T18:13:27.223Z","f3a8a3db","Plant Alpha",  "0fe3e48b","2017 Plant Study","06307ec0","A0043001","76.50106681","42.44409301","2017","Field_1","Plot_11","SubPlot_111","Plant_1111","Pot_1111","Block_11","Entry_11","Rep_11","25.3","", "",""
            
            "2019-09-10T18:14:27.223Z","f3a8a3db","Plant Alpha",  "0fe3e48b","2017 Plant Study","06307ec0","A0043001","76.50106681","42.44409301","2017","Field_1","Plot_11","SubPlot_111","Plant_1111","Pot_1111","Block_11","Entry_11","Rep_11","",    "3","",""
            
            "2019-09-10T18:15:54.868Z","05d1b011","Plant Beta",   "0fe3e48b","2017 Plant Study","59d435cd","A0043002","76.50106683","42.44409301","2017","Field_1","Plot_11","SubPlot_112","Plant_1122","Pot_1122","Block_11","Entry_11","Rep_12","27.9","", "",""
            
            "2019-09-10T18:16:54.868Z","05d1b011","Plant Beta",   "0fe3e48b","2017 Plant Study","59d435cd","A0043002","76.50106683","42.44409301","2017","Field_1","Plot_11","SubPlot_112","Plant_1122","Pot_1122","Block_11","Entry_11","Rep_12","",    "1","",""
            
            "2019-09-10T18:17:34.433Z","67e2d87c","Plant Gamma",  "0fe3e48b","2017 Plant Study","06307ec0","A0043001","76.50106681","42.44409356","2017","Field_1","Plot_12","SubPlot_123","Plant_1233","Pot_1233","Block_12","Entry_12","Rep_11","",    "3","",""
            
            "2019-09-10T18:18:34.433Z","67e2d87c","Plant Gamma",  "0fe3e48b","2017 Plant Study","06307ec0","A0043001","76.50106681","42.44409356","2017","Field_1","Plot_12","SubPlot_123","Plant_1233","Pot_1233","Block_12","Entry_12","Rep_11","25.5","", "",""
            
            "2019-09-10T18:19:15.629Z","d98d0d4c","Plant Epsilon","0fe3e48b","2017 Plant Study","59d435cd","A0043002","76.50106683","42.44409356","2017","Field_1","Plot_12","SubPlot_124","Plant_1244","Pot_1244","Block_12","Entry_12","Rep_12","28.9","", "",""
            
            "2019-09-10T18:20:15.629Z","d98d0d4c","Plant Epsilon","0fe3e48b","2017 Plant Study","59d435cd","A0043002","76.50106683","42.44409356","2017","Field_1","Plot_12","SubPlot_124","Plant_1244","Pot_1244","Block_12","Entry_12","Rep_12","",    "0","",""
          schema:
            type: string
        text/tsv:
          example: |-
            "observationUnitDbId"\t"observationUnitName"\t"studyDbId"\t"studyName"\t"germplasmDbId"\t"germplasmName"\t"positionCoordinateX"\t"positionCoordinateY"\t"year"\t"field"\t"plot"\t"sub-plot"\t"plant"\t"pot"\t"block"\t"entry"\t"rep"\t"f959a77d"\t"8341dee0"\t"84c9fd86"\t"93d80c95"
            
            ""\t""\t""\t""\t""\t""\t""\t""\t""\t""\t""\t""\t""\t""\t""\t""\t""\t"Plant height"\t"Carotenoid"\t"Root color"\t"Virus severity"
                  
            "2019-09-10T18:13:27.223Z"\t"f3a8a3db"\t"Plant Alpha"\t  "0fe3e48b"\t"2017 Plant Study"\t"06307ec0"\t"A0043001"\t"76.50106681"\t"42.44409301"\t"2017"\t"Field_1"\t"Plot_11"\t"SubPlot_111"\t"Plant_1111"\t"Pot_1111"\t"Block_11"\t"Entry_11"\t"Rep_11"\t"25.3"\t""\t ""\t""
            
            "2019-09-10T18:14:27.223Z"\t"f3a8a3db"\t"Plant Alpha"\t  "0fe3e48b"\t"2017 Plant Study"\t"06307ec0"\t"A0043001"\t"76.50106681"\t"42.44409301"\t"2017"\t"Field_1"\t"Plot_11"\t"SubPlot_111"\t"Plant_1111"\t"Pot_1111"\t"Block_11"\t"Entry_11"\t"Rep_11"\t""\t    "3"\t""\t""
            
            "2019-09-10T18:15:54.868Z"\t"05d1b011"\t"Plant Beta"\t   "0fe3e48b"\t"2017 Plant Study"\t"59d435cd"\t"A0043002"\t"76.50106683"\t"42.44409301"\t"2017"\t"Field_1"\t"Plot_11"\t"SubPlot_112"\t"Plant_1122"\t"Pot_1122"\t"Block_11"\t"Entry_11"\t"Rep_12"\t"27.9"\t""\t ""\t""
            
            "2019-09-10T18:16:54.868Z"\t"05d1b011"\t"Plant Beta"\t   "0fe3e48b"\t"2017 Plant Study"\t"59d435cd"\t"A0043002"\t"76.50106683"\t"42.44409301"\t"2017"\t"Field_1"\t"Plot_11"\t"SubPlot_112"\t"Plant_1122"\t"Pot_1122"\t"Block_11"\t"Entry_11"\t"Rep_12"\t""\t    "1"\t""\t""
            
            "2019-09-10T18:17:34.433Z"\t"67e2d87c"\t"Plant Gamma"\t  "0fe3e48b"\t"2017 Plant Study"\t"06307ec0"\t"A0043001"\t"76.50106681"\t"42.44409356"\t"2017"\t"Field_1"\t"Plot_12"\t"SubPlot_123"\t"Plant_1233"\t"Pot_1233"\t"Block_12"\t"Entry_12"\t"Rep_11"\t""\t    "3"\t""\t""
            
            "2019-09-10T18:18:34.433Z"\t"67e2d87c"\t"Plant Gamma"\t  "0fe3e48b"\t"2017 Plant Study"\t"06307ec0"\t"A0043001"\t"76.50106681"\t"42.44409356"\t"2017"\t"Field_1"\t"Plot_12"\t"SubPlot_123"\t"Plant_1233"\t"Pot_1233"\t"Block_12"\t"Entry_12"\t"Rep_11"\t"25.5"\t""\t ""\t""
            
            "2019-09-10T18:19:15.629Z"\t"d98d0d4c"\t"Plant Epsilon"\t"0fe3e48b"\t"2017 Plant Study"\t"59d435cd"\t"A0043002"\t"76.50106683"\t"42.44409356"\t"2017"\t"Field_1"\t"Plot_12"\t"SubPlot_124"\t"Plant_1244"\t"Pot_1244"\t"Block_12"\t"Entry_12"\t"Rep_12"\t"28.9"\t""\t ""\t""
            
            "2019-09-10T18:20:15.629Z"\t"d98d0d4c"\t"Plant Epsilon"\t"0fe3e48b"\t"2017 Plant Study"\t"59d435cd"\t"A0043002"\t"76.50106683"\t"42.44409356"\t"2017"\t"Field_1"\t"Plot_12"\t"SubPlot_124"\t"Plant_1244"\t"Pot_1244"\t"Block_12"\t"Entry_12"\t"Rep_12"\t""\t    "0"\t""\t""
          schema:
            type: string
      description: OK
      headers: {}
