info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths: {}
components:
  schemas:
    GermplasmAttributeValue: 
      allOf:
      - $ref: '#/components/schemas/GermplasmAttributeValueNewRequest'
      - properties: 
          attributeValueDbId:
            description: The ID which uniquely identifies this attribute value within the given database server
            type: string
            example: 33edbab7
        required: 
        - attributeValueDbId
        type: object
        x-brapi-metadata:
          primaryModel: true
          module: BrAPI-Germplasm
          title: GermplasmAttributeValue
          description: The value recorded for a particular Trait/Attribute and a particular Germplasm. Similar to an Observation value, but more concrete, applying to the whole Germplasm instead of a single ObservationUnit.  

