info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths: {}
components:
  schemas:
    callSetsSearchRequest: 
      allOf:
      - $ref: '#/components/schemas/SearchRequestParametersPaging'
      - $ref: '#/components/schemas/SearchRequestParametersGermplasm'
      - $ref: '#/components/schemas/SearchRequestParametersCommonCropNames'
      - $ref: '#/components/schemas/SearchRequestParametersPrograms'
      - $ref: '#/components/schemas/SearchRequestParametersTrials'
      - $ref: '#/components/schemas/SearchRequestParametersStudies'
      - $ref: '#/components/schemas/SearchRequestParametersExternalReferences'
      - type: object
        properties:
          sampleDbIds:
            description: A list of IDs which uniquely identify `Samples` within the given database server 
            type: array
            items:
              type: string
            example: [ '758d3f6d', '39c0a3f7']
          sampleNames:
            description: A list of human readable names associated with `Samples`
            type: array
            items:
              type: string
            example: [ 'Sample_123', 'Sample_789' ]
          callSetDbIds: 
            description: A list of IDs which uniquely identify `CallSets` within the given database server 
            type: array
            items:
              type: string
            example: [ '6c7486b2', '49c36a73']
          callSetNames:
            description: A list of human readable names associated with `CallSets`
            type: array
            items:
              type: string
            example: [ 'Sample_123_DNA_Run_456', 'Sample_789_DNA_Run_101' ]
          variantSetDbIds: 
            description: A list of IDs which uniquely identify `VariantSets` within the given database server 
            type: array
            items:
              type: string
            example: [ '8a9a8972', '32a2649a']
