info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths: {}
components:
  responses:
    CallSetsListResponse:
      description: OK
      headers: {}
      content:
        application/json:
          schema:
            title: CallSetsListResponse
            type: object
            required:
            - metadata
            - result
            properties:
              '@context':
                $ref: '#/components/schemas/Context'
              metadata:
                $ref: '#/components/schemas/metadata'
              result:
                title: CallSetsListResponseResult
                type: object
                required:
                - data
                properties:
                  data:
                    description: The `data` array is part of the BrAPI standard List Response JSON container. `data` will always contain the primary list of objects being returned by a BrAPI endpoint. `data` is also the only array impacted by the `metadata.pagination` details. When the pagination parameters change, the `data` array will reflect those changes in the JSON response.
                    items:
                      $ref: '#/components/schemas/CallSet'
                    type: array
                    