info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths:
  /commoncropnames:
    get:
      summary: Get the Common Crop Names
      description: |-
        List the common crop names for the crops available in a database server. 
        
        This call is ** required ** for multi-crop systems where data from multiple 
        crops may be stored in the same database server. A distinct database server 
        is defined by everything in the URL before "/brapi/v2", including host 
        name and base path.
        
        This call is recommended for single crop systems to be compatible with 
        multi-crop clients. For a single crop system the response should contain 
        an array with exactly 1 element. 
        
        The common crop name can be used as a search parameter for Programs, 
        Studies, and Germplasm.
      parameters:
      - $ref: '#/components/parameters/page'
      - $ref: '#/components/parameters/pageSize'
      - $ref: '#/components/parameters/authorizationHeader'
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  '@context':
                    $ref: '#/components/schemas/Context'
                  metadata:
                    $ref: '#/components/schemas/metadata'
                  result:
                    properties:
                      data:
                        description: The array of crop names available on the server
                        items:
                          description: supported crop name
                          type: string
                        type: array
                        example: ['Tomatillo', 'Paw Paw']
                    required:
                    - data
                    type: object
                required:
                - metadata
                - result
                title: commonCropNamesResponse
                type: object
          description: OK
          headers: {}
        '400':
          $ref: '#/components/responses/400BadRequest'
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '403':
          $ref: '#/components/responses/403Forbidden'
      tags:
      - Common Crop Names
