info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths: {}
components:
  schemas:
    ObservationVariableNewRequest:
      allOf:
      - $ref: '#/components/schemas/VariableBaseClass'
      - type: object
        properties:
          observationVariableName:
            description: Human readable name of an Observation Variable
            type: string
            example: Variable Name
          observationVariablePUI:
            description: The Permanent Unique Identifier of a Observation Variable, usually in the form of a URI
            type: string
            example: http://my-traits.com/trait/CO_123:0009012
        required:
        - observationVariableName