info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths: {}
components:
  schemas:
    ObservationVariable:
      allOf:
      - $ref: '#/components/schemas/ObservationVariableNewRequest'
      - properties:
          observationVariableDbId:
            description: |-
              Variable unique identifier
              
              MIAPPE V1.1 (DM-83) Variable ID - Code used to identify the variable in the data file. We recommend using a variable definition from the Crop Ontology where possible. Otherwise, the Crop Ontology naming convention is recommended: <trait abbreviation>_<method abbreviation>_<scale abbreviation>). A variable ID must be unique within a given investigation.
            type: string
            example: b9b7edd1
          observationVariableName:
            description: |-
              Variable name (usually a short name)
              
              MIAPPE V1.1 (DM-84) Variable name - Name of the variable.
            type: string
            example: Variable Name
        required:
        - observationVariableDbId
        - observationVariableName
        type: object
        x-brapi-metadata:
          primaryModel: true
          module: BrAPI-Phenotyping
          title: ObservationVariable
          description: A unique combination of Trait, Method, and Scale to define a clear context for an Observation. 

