info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths: {}
components:
  schemas:
    ObservationVariableSearchRequest:
      allOf:
      - $ref: '#/components/schemas/SearchRequestParametersVariableBaseClass'
      - $ref: '#/components/schemas/SearchRequestParametersObservationVariables'
  