info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths: {}
components:
  responses:
    MatrixResponse:
      content:
        application/json:
          schema:
            title: MatrixResponse
            properties:
              '@context':
                $ref: '#/components/schemas/Context'
              metadata:
                $ref: '#/components/schemas/metadata'
              result:
                properties:
                  data:
                    items:
                      $ref: '#/components/schemas/ObservationVector'
                    type: array
                required:
                - data
                type: object
            required:
            - metadata
            - result
            type: object
      description: OK
      headers: {}