info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths:
  /seedlots:
    get:
      summary: Get a filtered list of Seed Lot descriptions
      description: Get a filtered list of Seed Lot descriptions available in a system.
      parameters:
      - name: seedLotDbId
        description: Unique id for a seed lot on this server
        in: query
        required: false
        schema:
          type: string 
      - name: crossDbId 
        description: Search for Cross with this unique id
        in: query
        required: false
        schema:
          type: string
      - name: crossName
        description: Search for Cross with this human readable name
        in: query
        required: false
        schema:
          type: string
      - $ref: '#/components/parameters/commonCropName'
      - $ref: '#/components/parameters/programDbId'
      - $ref: '#/components/parameters/germplasmDbId'
      - $ref: '#/components/parameters/germplasmName'
      - $ref: '#/components/parameters/externalReferenceID'
      - $ref: '#/components/parameters/externalReferenceId'
      - $ref: '#/components/parameters/externalReferenceSource'
      - $ref: '#/components/parameters/page'
      - $ref: '#/components/parameters/pageSize'
      - $ref: '#/components/parameters/authorizationHeader'
      responses:
        '200':
          $ref: '#/components/responses/SeedLotListResponse'
        '400':
          $ref: '#/components/responses/400BadRequest'
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '403':
          $ref: '#/components/responses/403Forbidden'
      tags:
      - Seed Lots
    post:
      summary: Add new Seed Lot descriptions to a server
      description: Add new Seed Lot descriptions to a server
      parameters:
      - $ref: '#/components/parameters/authorizationHeader'
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items: 
                $ref: '#/components/schemas/SeedLotNewRequest'
      responses:
        '200':
          $ref: '#/components/responses/SeedLotListResponse'
        '400':
          $ref: '#/components/responses/400BadRequest'
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '403':
          $ref: '#/components/responses/403Forbidden'
      tags:
      - Seed Lots
components:
  responses:
    SeedLotListResponse:
      content:
        application/json:
          schema:
            title: SeedLotListResponse
            type: object
            properties:
              '@context':
                $ref: '#/components/schemas/Context'
              metadata:
                $ref: '#/components/schemas/metadata'
              result:
                properties:
                  data:
                    description: The `data` array is part of the BrAPI standard List Response JSON container. `data` will always contain the primary list of objects being returned by a BrAPI endpoint. `data` is also the only array impacted by the `metadata.pagination` details. When the pagination parameters change, the `data` array will reflect those changes in the JSON response.
                    items:
                      $ref: '#/components/schemas/SeedLot'
                    type: array
                required:
                - data
                type: object
            required:
            - metadata
            - result
      description: OK
      headers: {}
    
