info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths: {}
components:
  parameters:
    programDbId:
      name: programDbId
      description: |-
        Use this parameter to only return results associated with the given `Program` unique identifier. 
        <br/>Use `GET /programs` to find the list of available `Programs` on a server.
      in: query
      required: false
      schema:
        type: string
    programName:
      name: programName
      description: |-
        Use this parameter to only return results associated with the given `Program` by its human readable name. 
        <br/>Use `GET /programs` to find the list of available `Programs` on a server.
      in: query
      required: false
      schema:
        type: string
    trialDbId:
      name: trialDbId
      description: |-
        Use this parameter to only return results associated with the given `Trial` unique identifier. 
        <br/>Use `GET /trials` to find the list of available `Trials` on a server.
      in: query
      required: false
      schema:
        type: string
    trialName:
      name: trialName
      description: |-
        Use this parameter to only return results associated with the given `Trial` by its human readable name. 
        <br/>Use `GET /trials` to find the list of available `Trials` on a server.
      in: query
      required: false
      schema:
        type: string
    studyDbId:
      name: studyDbId
      description: |-
        Use this parameter to only return results associated with the given `Study` unique identifier. 
        <br/>Use `GET /studies` to find the list of available `Studies` on a server.
      in: query
      required: false
      schema:
        type: string
    studyName:
      name: studyName
      description: |-
        Use this parameter to only return results associated with the given `Study` by its human readable name. 
        <br/>Use `GET /studies` to find the list of available `Studies` on a server.
      in: query
      required: false
      schema:
        type: string

