info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths: {}
components:
  schemas:
    ObservationUnitHierarchyLevel: 
      title: ObservationUnitHierarchyLevel
      type: object
      description: |-
        Observation levels indicate the granularity level at which the measurements are taken. `levelName` 
        defines the level, `levelOrder` defines where that level exists in the hierarchy of levels. 
        `levelOrder`s lower numbers are at the top of the hierarchy (ie field > 0) and higher numbers are 
        at the bottom of the hierarchy (ie plant > 6). 

        **Standard Level Names: study, field, entry, rep, block, sub-block, plot, sub-plot, plant, pot, sample** 

        For more information on Observation Levels, please review the <a target="_blank" href="https://wiki.brapi.org/index.php/Observation_Levels">Observation Levels documentation</a>. 
      properties:
        levelName: 
          description: |-
            A name for this level 

            **Standard Level Names: study, field, entry, rep, block, sub-block, plot, sub-plot, plant, pot, sample** 

            For more information on Observation Levels, please review the <a target="_blank" href="https://wiki.brapi.org/index.php/Observation_Levels">Observation Levels documentation</a>. 
          type: string
          example: plot
        levelOrder: 
          description: |-
            `levelOrder` defines where that level exists in the hierarchy of levels. `levelOrder`'s lower numbers 
            are at the top of the hierarchy (ie field -> 1) and higher numbers are at the bottom of the hierarchy (ie plant -> 9). 

            For more information on Observation Levels, please review the <a target="_blank" href="https://wiki.brapi.org/index.php/Observation_Levels">Observation Levels documentation</a>. 
          type: integer
          example: 2