info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths: {}
components:
  schemas:
    ScaleBaseClass:
      type: object
      description: |-
        A Scale describes the units and acceptable values for an ObservationVariable. 
        <br>For example, an ObservationVariable might be defined with a Trait of "plant height", a Scale of "meters", and a Method of "tape measure". This variable would be distinct from a variable with the Scale "inches" or "pixels".
      required:
      - scaleName
      properties:
        additionalInfo:
          additionalProperties:
            type: string
          description: A free space containing any additional information related to a particular object. A data source may provide any JSON object, unrestricted by the BrAPI specification.
          type: object
        dataType:
          $ref: '#/components/schemas/TraitDataType'
        decimalPlaces:
          description: For numerical, number of decimal places to be reported
          type: integer
          example: 2
        ontologyReference:
          $ref: '#/components/schemas/OntologyReference'
        scaleName:
          description: |- 
            Name of the scale
            <br/>MIAPPE V1.1 (DM-92) Scale Name of the scale associated with the variable
          type: string
          example: Meters
        scalePUI:
          description: The Permanent Unique Identifier of a Scale, usually in the form of a URI
          type: string
          example: http://my-traits.com/trait/CO_123:0000112
        units:
          description: |-
            This field can be used to describe the units used for this scale. This should be the abbreviated 
            form of the units, intended to be displayed with every value using this scale. Usually this only 
            applies when `dataType` is Numeric, but could also be included for other dataTypes when applicable.
          type: string
          example: m
        validValues:
          type: object
          properties:
            categories: 
              description: List of possible values with optional labels
              items:
                type: object
                properties:
                  label:
                    type: string 
                    description: A text label for a category
                  value:
                    type: string
                    description: The actual value for a category
              type: array
              example: 
                - value: "0"
                  label: "low"
                - value: "5"
                  label: "medium"
                - value: "10"
                  label: "high"
            max:
              description: |-
                **Deprecated in v2.1** Please use `maximumValue`. Github issue number #450 
                <br>Maximum value for numerical scales. Typically used for data capture control and QC.
              type: integer
              example: 9999
              deprecated: true
            min:
              description: |-
                **Deprecated in v2.1** Please use `minimumValue`. Github issue number #450 
                <br>Minimum value for numerical scales. Typically used for data capture control and QC.
              type: integer
              example: 2
              deprecated: true
            maximumValue:
              description: Maximum value for numerical, date, and time scales. Typically used for data capture control and QC.
              type: string
              example: '9999'
            minimumValue:
              description: Minimum value for numerical, date, and time scales. Typically used for data capture control and QC.
              type: string
              example: '2'
        externalReferences: 
          $ref: '#/components/schemas/ExternalReferences'

