info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths: {}
components:
  parameters:
    searchResultsDbId:
      description: Unique identifier which references the search results
      in: path
      name: searchResultsDbId
      required: true
      schema:
        type: string
    preview:
      name: preview
      description: |- 
            Default Value = false
            <br/>If 'preview' is set to true, then the server should return with the "dataMatrices" field as null or empty. All other data fields should be returned normally. 
            This is intended to be a preview and give the client a sense of how large the matrix returned will be
            <br/>If 'preview' is set to false or not set (default), then the server should return all the matrix data as requested.
      in: query
      required: false
      schema:
        type: boolean
    dataMatrixNames:
      name: dataMatrixNames
      description: |-
        "dataMatrixNames" is a comma seperated list of names (ie 'Genotype, Read Depth' etc). This list controls which data matrices are returned in the response.
        <br> This maps to a FORMAT field in the VCF file standard.
      in: query
      required: false
      schema:
        type: string
    dataMatrixAbbreviations:
      name: dataMatrixAbbreviations
      description: |-
        "dataMatrixAbbreviations" is a comma seperated list of abbreviations (ie 'GT, RD' etc). This list controls which data matrices are returned in the response.
        <br> This maps to a FORMAT field in the VCF file standard.
      in: query
      required: false
      schema:
        type: string
    callSetDbId:
      name: callSetDbId
      description: The ID which uniquely identifies a `CallSet` within the given database server 
      in: query
      required: false
      schema:
        type: string
    variantDbId:
      name: variantDbId
      description: The ID which uniquely identifies a `Variant` within the given database server 
      in: query
      required: false
      schema:
        type: string
    variantSetDbId:
      name: variantSetDbId
      description: The ID which uniquely identifies a `VariantSet` within the given database server 
      in: query
      required: false
      schema:
        type: string
    expandHomozygotes:
      name: expandHomozygotes
      description: Should homozygotes be expanded (true) or collapsed into a single occurrence (false)
      in: query
      required: false
      schema:
        type: boolean
    unknownString:
      name: unknownString
      description: The string to use as a representation for missing data
      in: query
      required: false
      schema:
        type: string
    sepPhased: 
      name: sepPhased
      description: The string to use as a separator for phased allele calls
      in: query
      required: false
      schema:
        type: string
    sepUnphased: 
      name: sepUnphased
      description: The string to use as a separator for unphased allele calls
      in: query
      required: false
      schema:
        type: string
    positionRange:
      name: positionRange
      description: |-
        The postion range to search
        <br/> Uses the format "contig:start-end" where "contig" is the chromosome or contig name, "start" is  
        the starting position of the range, and "end" is the ending position of the range
        <br> Example: CRHOM_1:12000-14000
      in: query
      required: false
      schema:
        type: string
