info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths: {}
components:
  schemas:
    ImageMutationRunRequest:
      type: object
      properties:
        inputImageDbIds:
          description: List of images to be used as input for a mutation run
          type: array
          items:
            type: string
          example: [34a22db7]
        inputImageCollectionDbIds:
          description: List of image collections to be used as input for a mutation run
          type: array
          items:
            type: string
          example: []
        imageMutationDbId:
          description: Unique database identifier for an image mutation
          type: string
          example: 224ab7d3
        imagingEventDbId:
          description: Unique database identifier for an imaging event
          type: string
          example: 32aa577d
        imageMutationParameters:
          description: list of parameters set for a specific image mutation run
          type: array
          items:
            type: object
            properties:
              parameterName:
                description: the human readable name of an image mutation parameter
                type: string
                example: lower_threshold
              parameterValue:
                description: the value of an image mutation parameter
                type: string
                example: 20


