info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths: {}
components:
  schemas:
    ImageMutation:
      type: object
      properties:
        additionalInfo:
          additionalProperties:
            type: string
          description: A free space containing any additional information related to a particular object. A data source may provide any JSON object, unrestriced by the BrAPI specification.  
          type: object
        externalReferences: 
          $ref: '#/components/schemas/ExternalReferences'
        imageMutationDbId:
          description: Unique database identifier for an image mutation
          type: string
          example: 224ab7d3
        imageMutationName:
          description: Human readable name for an image mutation
          type: string
          example: Remove Background
        imageMutationDescription:
          description: Human readable description of an image mutation
          type: string
          example: For removing the background using an upper and lower threshold. Uses OpenCV threshold.
        imageInputType:
          description: The type of input an image mutation is expecting. A single image, a list/collection of images, or a list of image collections.
          type: array
          items:
            type: string
            enum: 
            - IMAGE_SINGLE
            - IMAGE_LIST
            - IMAGE_COLLECTION_SINGLE
            - IMAGE_COLLECTION_LIST
          example: 
          - IMAGE_LIST
          - IMAGE_COLLECTION_SINGLE
        imageMutationParameters:
          description: list of possible parameters used by an image mutation
          type: array
          items:
            type: object
            properties:
              parameterName: 
                description: the human readable name of an image mutation parameter
                type: string
                example: image_type
              parameterType:
                description: the data type of an image mutation parameter (string, integer, boolean, etc)
                type: string
                example: string
              required:
                description: True if the parameter is required for the image mutation to run properly
                type: boolean
                example: true
              valueOptions:
                description: If the parameter will only accept certain values, list those values here. 
                type: array
                items:
                  type: string
                example: [threshold_background_removed_tgi_stitched_drone_imagery, threshold_background_removed_vari_stitched_drone_imagery, threshold_background_removed_ndvi_stitched_drone_imagery, threshold_background_removed_stitched_drone_imagery]