info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths: {}
components:
  schemas:
    Program:
      allOf:
      - $ref: '#/components/schemas/ProgramNewRequest'
      - type: object
        x-brapi-metadata:
          primaryModel: true
          module: BrAPI-Core
          title: Program
          description: A BrAPI Program represents the high level organization or group who is responsible for conducting trials and studies. Things like Breeding Programs and Funded Projects are considered BrAPI Programs. A Program can contain multiple Trials. A Trial can contain multiple Studies. 
        required:
        - programDbId
        properties:
          programDbId:
            description: The ID which uniquely identifies the program
            type: string
            example: f60f15b2

