info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths:
  /imagemutationruns:
    post:
      summary: Get filtered set of image mutations
      description: |-
        Get filtered set of image mutations
      parameters:
      - $ref: '#/components/parameters/authorizationHeader'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ImageMutationRunRequest'
      responses:
        '200':
          $ref: '#/components/responses/ImageMutationRunListResponse'
        '400':
          $ref: '#/components/responses/400BadRequest'
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '403':
          $ref: '#/components/responses/403Forbidden'
      tags:
      - Image Mutations
components:
  responses:
    ImageMutationRunListResponse:
      content:
        application/json:
          schema:
            title: ImageMutationRunListResponse
            type: object
            properties:
              '@context':
                $ref: '#/components/schemas/Context'
              metadata:
                $ref: '#/components/schemas/metadata'
              result:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/ImageMutationRunResponse'
                required:
                - data
            required:
            - metadata
            - result
      description: OK
      headers: {}
      
