info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths:
  /attributes/categories:
    get:
      summary: Get the Categories of Germplasm Attributes
      description: List all available attribute categories.
      parameters:
      - $ref: '#/components/parameters/page'
      - $ref: '#/components/parameters/pageSize'
      - $ref: '#/components/parameters/authorizationHeader'
      responses:
        '200':
          content:
            application/json:
              schema:
                title: GermplasmAttributeCategoryListResponse
                type: object
                properties:
                  '@context':
                    $ref: '#/components/schemas/Context'
                  metadata:
                    $ref: '#/components/schemas/metadata'
                  result:
                    properties:
                      data:
                        description: The `data` array is part of the BrAPI standard List Response JSON container. `data` will always contain the primary list of objects being returned by a BrAPI endpoint. `data` is also the only array impacted by the `metadata.pagination` details. When the pagination parameters change, the `data` array will reflect those changes in the JSON response.
                        items:
                          type: string
                        type: array
                        example:
                        - Morphological
                        - Agronomic
                    required:
                    - data
                    type: object
                required:
                - metadata
                - result
          description: OK
          headers: {}
        '400':
          $ref: '#/components/responses/400BadRequest'
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '403':
          $ref: '#/components/responses/403Forbidden'
      tags:
      - Germplasm Attributes
