info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths:
  /attributes:
    get:
      summary: Get the Germplasm Attributes
      description: List available attributes.
      parameters:
      - name: attributeCategory
        description: The general category for the attribute. very similar to Trait class.
        in: query
        required: false
        schema:
          type: string
      - name: attributeDbId
        description: The unique id for an attribute
        in: query
        required: false
        schema:
          type: string
      - name: attributeName
        description: The human readable name for an attribute
        in: query
        required: false
        schema:
          type: string
      - name: attributePUI
        description: The Permanent Unique Identifier of an Attribute, usually in the form of a URI
        in: query
        required: false
        schema:
          type: string
      - $ref: '#/components/parameters/methodDbId'
      - $ref: '#/components/parameters/methodName'
      - $ref: '#/components/parameters/methodPUI'
      - $ref: '#/components/parameters/scaleDbId'
      - $ref: '#/components/parameters/scaleName'
      - $ref: '#/components/parameters/scalePUI'
      - $ref: '#/components/parameters/traitDbId'
      - $ref: '#/components/parameters/traitName'
      - $ref: '#/components/parameters/traitPUI'
      - $ref: '#/components/parameters/commonCropName'
      - $ref: '#/components/parameters/programDbId'
      - $ref: '#/components/parameters/germplasmDbId'
      - $ref: '#/components/parameters/externalReferenceID'
      - $ref: '#/components/parameters/externalReferenceId'
      - $ref: '#/components/parameters/externalReferenceSource'
      - $ref: '#/components/parameters/page'
      - $ref: '#/components/parameters/pageSize'
      - $ref: '#/components/parameters/authorizationHeader'
      responses:
        '200':
          $ref: '#/components/responses/GermplasmAttributeListResponse'
        '400':
          $ref: '#/components/responses/400BadRequest'
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '403':
          $ref: '#/components/responses/403Forbidden'
      tags:
      - Germplasm Attributes
    post:
      summary: Create new Germplasm Attributes
      description: Create new Germplasm Attributes
      parameters:
      - $ref: '#/components/parameters/authorizationHeader'
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items: 
                $ref: '#/components/schemas/GermplasmAttributeNewRequest'
      responses:
        '200':
          $ref: '#/components/responses/GermplasmAttributeListResponse'
        '400':
          $ref: '#/components/responses/400BadRequest'
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '403':
          $ref: '#/components/responses/403Forbidden'
      tags:
      - Germplasm Attributes
components:
  responses:
    GermplasmAttributeListResponse:
      content:
        application/json:
          schema:
            title: GermplasmAttributeListResponse
            type: object
            properties:
              '@context':
                $ref: '#/components/schemas/Context'
              metadata:
                $ref: '#/components/schemas/metadata'
              result:
                properties:
                  data:
                    description: The `data` array is part of the BrAPI standard List Response JSON container. `data` will always contain the primary list of objects being returned by a BrAPI endpoint. `data` is also the only array impacted by the `metadata.pagination` details. When the pagination parameters change, the `data` array will reflect those changes in the JSON response.
                    items:
                      $ref: '#/components/schemas/GermplasmAttribute'
                    type: array
                required:
                - data
                type: object
            required:
            - metadata
            - result
      description: OK
      headers: {}
    
