info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths:
  /variants/{variantDbId}:
    get:
      summary: Gets a `Variant` by ID.
      description: The endpoint `GET /variants/{id}` will return a JSON version of `Variant`.
      parameters:
        - name: variantDbId
          description: The ID which uniquely identifies a `Variant`
          in: path
          required: true
          schema:
            type: string
        - $ref: '#/components/parameters/authorizationHeader'
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                title: VariantSingleResponse
                type: object
                required:
                - metadata
                - result
                properties:
                  '@context':
                    $ref: '#/components/schemas/Context'
                  metadata:
                    $ref: '#/components/schemas/metadata'
                  result:
                    $ref: '#/components/schemas/Variant'
        '400':
          $ref: '#/components/responses/400BadRequest'
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '403':
          $ref: '#/components/responses/403Forbidden'
        '404':
          $ref: '#/components/responses/404NotFound'
      tags:
        - Variants