info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths:
  /variants:
    get:
      summary: Gets a filtered list of `Variants`.
      description: |-
        Gets a filtered list of `Variants`.
      parameters:
        - name: variantDbId
          description: The ID which uniquely identifies a `Variant`
          in: query
          required: false
          schema:
            type: string
        - name: variantSetDbId
          description: The ID which uniquely identifies a `VariantSet`
          in: query
          required: false
          schema:
            type: string
        - name: referenceDbId
          description: The ID which uniquely identifies a `Reference`
          in: query
          required: false
          schema:
            type: string
        - name: referenceSetDbId
          description: The ID which uniquely identifies a `ReferenceSet`
          in: query
          required: false
          schema:
            type: string
        - $ref: '#/components/parameters/pageToken'
        - $ref: '#/components/parameters/page'
        - $ref: '#/components/parameters/pageSize'
        - $ref: '#/components/parameters/externalReferenceId'
        - $ref: '#/components/parameters/externalReferenceSource'
        - $ref: '#/components/parameters/authorizationHeader'
      responses:
        '200':
          $ref: '#/components/responses/VariantsListResponse'
        '400':
          $ref: '#/components/responses/400BadRequest'
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '403':
          $ref: '#/components/responses/403Forbidden'
      tags:
        - Variants