info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths: {}
components:
  schemas:
    Cross:
      allOf:
        - $ref: '#/components/schemas/CrossNewRequest'
        - type: object
          x-brapi-metadata:
            primaryModel: true
            module: BrAPI-Germplasm
            title: Cross
            description: The identifiers and metadata represent that specific organisms have mated to produce offspring with particular traits or genes. The offspring of a Cross might be developed into a Germplasm if the desired traits are present. 
          required:
          - crossDbId
          properties:
            crossDbId:
              description: the unique identifier for a cross
              type: string
              example: d105fd6f