info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths: {}
components:
  schemas:
    Call:
      type: object
      description: |-
        A `Call` represents the determination of genotype with respect to a particular `Variant`.
        <br/>It may include associated information such as quality and phasing. For example, a call .
        might assign a probability of 0.32 to the occurrence of a SNP named RS_1234 in a call set with the name NA_12345.
      properties:
        additionalInfo:
          additionalProperties:
            type: string
          description: Additional arbitrary info
          type: object
        callSetDbId:
          description: |-
            The ID of the call set this variant call belongs to.
            <br/>If this field is not present, the ordering of the call sets from a `SearchCallSetsRequest` over this `VariantSet` 
            is guaranteed to match the ordering of the calls on this `Variant`. The number of results will also be the same.
          type: string
          example: 16466f55
        callSetName:
          description: The name of the call set this variant call belongs to. If this field is not present, the ordering of the call sets from a `SearchCallSetsRequest` over this `VariantSet` is guaranteed to match the ordering of the calls on this `Variant`. The number of results will also be the same.
          type: string
          example: Sample_123_DNA_Run_456
        variantDbId:
          description: The ID of the Variant this call belongs to.
          type: string
          example: 538c8ecf
        variantName:
          description: The name of the Variant this call belongs to.
          type: string
          example: Marker A
        variantSetDbId:
          description: The ID of the Variant Set this call belongs to.
          type: string
          example: 8c8ecf53
        variantSetName:
          description: The name of the Variant Set this call belongs to.
          type: string
          example: Marker A
        genotype:
          description: The value of this genotype 
          type: string
          example: '1/1'
        genotypeMetadata:
          description: Genotype Metadata are additional layers of metadata associated with each genotype.
          type: array
          items:
            type: object
            properties:
              dataType:
                description: The type of field represented in this Genotype Field. This is intended to help parse the data out of JSON.
                type: string
                enum:
                - string
                - integer
                - float
                - boolean
                example: integer
              fieldName:
                description: |-
                  The name of the field represented in this Genotype Field. Examples include: "Genotype Quality", "Read Depth", and "Haplotype Quality"
                type: string
                example: Genotype Quality
              fieldAbbreviation:
                description: |-
                  The abbreviated code of the field represented in this Genotype Field. These codes should match the VCF standard when possible. Examples include: "GQ", "RD", and "HQ"
                type: string
                example: GQ
              fieldValue:
                description: The additional metadata value associated with this genotype call
                type: string
                example: '45.2'
        phaseSet:
          description: |-
            If this field is populated, this variant call's genotype ordering implies the phase of the bases and 
            is consistent with any other variant calls on the same contig which have the same phase set string.
          type: string
          example: 6410afc5

