info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths: {}
components:
  schemas:
    ListValue:
      type: object
      description: |-
        `ListValue` is a wrapper around a repeated field of values.

        The JSON representation for `ListValue` is JSON array.
      properties:
        values:
          type: array
          description: Repeated field of dynamically typed values.
          items:
            oneOf:
            - description: Represents a boolean value.
              format: boolean
              type: boolean
            - description: Represents a double value.
              format: double
              type: number
            - description: Represents a string value.
              type: string
          example: [ 'AA' ]
