info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths: {}
components:
  schemas:
    CallsSearchRequest: 
      type: object
      properties:
        positionRanges:
          description: |-
            The postion range to search
            <br/>
            Uses the format "<chrom>:<start>-<end>" where <chrom> is the chromosome name, <start> is 
            the starting position of the range, and <end> is the ending position of the range
          type: array
          items:
            type: string
          example: [ '20:1000-35000', '20:87000-125000' ]
        germplasmNames:
          description: The germplasm to search
          type: array
          items:
            type: string
          example: [ 'a03202ec', '274e4f63' ]
        germplasmPUIs:
          description: The germplasm to search
          type: array
          items:
            type: string
          example: [ 'a03202ec', '274e4f63' ]
        germplasmDbIds:
          description: The germplasm to search
          type: array
          items:
            type: string
          example: [ 'a03202ec', '274e4f63' ]
        sampleDbIds:
          description: The samples to search
          type: array
          items:
            type: string
          example: [ 'a03202ec', '274e4f63' ]
        callSetDbIds:
          description: The CallSet to search.
          type: array
          items:
            type: string
          example: [ 'a03202ec', '274e4f63' ]
        variantDbIds: 
          description: The Variant to search.
          type: array
          items:
            type: string
          example: [ 'bba0b258', 'ff97d4f0' ]
        variantSetDbIds: 
          description: The VariantSet to search.
          type: array
          items:
            type: string
          example: [ '407c0508', '49e24dfc' ]
        expandHomozygotes:
          description: Should homozygotes be expanded (true) or collapsed into a single occurrence (false)
          type: boolean
          example: true
        sepPhased:
          description: The string used as a separator for phased allele calls.
          type: string
          example: '|'
        sepUnphased:
          description: The string used as a separator for unphased allele calls.
          type: string
          example: '/'
        unknownString:
          description: The string used as a representation for missing data.
          type: string
          example: '.'
