info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths: {}
components:
  schemas:
    VariantMatrix:
      type: object
      required:
      - data
      properties:
        pagination:
          description: Pagination for the matrix
          type: array
          items:
            type: object
            properties:
              dimension:
                description: the dimension of the matrix being paginated
                type: string
                enum:
                - CALLSETS
                - VARIANTS
                example: VARIANTS
              pageSize: 
                description: the maximum number of elements per page in this dimension of the matrix
                type: integer
                example: 500
              page: 
                description: the requested page number (zero indexed) 
                type: integer
                example: 0
              totalCount:
                description: The total number of elements that are available on the server and match the requested query parameters. 
                type: integer
                example: 10000
              totalPages:
                description: |-
                  The total number of pages of elements available on the server. This should be calculated with the following formula. 
                  <br/>totalPages = CEILING( totalCount / requested_page_size)
                type: integer
                example: 20
          example:
            -  dimension: VARIANTS
               pageSize: 500
               page: 0
               totalCount: 10000
               totalPages: 20
            -  dimension: CALLSETS
               pageSize: 1000
               page: 4
               totalCount: 10000
               totalPages: 10
        callSetDbIds:
          type: array
          items:
            type: string
          example: ['aca00001', 'aca00002', 'aca00003']
        variantSetDbIds:
          type: array
          items:
            type: string
          example: ['cfde3944', 'cfde2077', 'cfde4424']
        variants:
          type: array
          items:
            type: object
            properties:
              variantDbId:
                type: string
              contig: 
                type: string
              start:
                type: integer
              end:
                type: integer
              ploidy:
                type: integer
          example: [{'variantDbId': 'feb54257', 'contig': 'CHROM20', 'start': 14370, 'end': 24370, 'ploidy': 2},
                    {'variantDbId': 'feb40355', 'contig': 'CHROM20', 'start': 1110696, 'end': 1113696, 'ploidy': 2},
                    {'variantDbId': 'feb40323', 'contig': 'CHROM20', 'start': 1234567, 'end': 1237567, 'ploidy': 2}]
        data:
          type: array
          items:
            type: array
            items:
              type: string
          example:
          - ['0|0', '1|0', '1/1']
          - ['0|0', '1|0', '1/1']
          - ['0|0', '1|0', '1/1']
        genotypeFields:
          type: array
          items:
            type: object
            properties:
              fieldType:
                type: string
                enum:
                - string
                - integer
                - float
                - boolean
                example: integer
              fieldName:
                type: string
                enum:
                - Genotype Quality
                - Read Depth
                - Haplotype Quality
                example: Genotype Quality
              fieldAbbreviation:
                type: string
                enum:
                - GQ
                - RD
                - HQ
                example: GQ
              fieldMatrix:
                type: array
                items:
                  type: array
                  items:
                    type: string
                example:
                - ['48', '48', '43']
                - ['49', '3', '41']
                - ['21', '2', '35']
        expandHomozygotes: 
          description: Should homozygotes be expanded (true) or collapsed into a single occurrence (false)
          type: boolean
          example: true
        sepPhased:
          description: The string used as a separator for phased allele calls.
          type: string
          example: '|'
        sepUnphased:
          description: The string used as a separator for unphased allele calls.
          type: string
          example: '/'
        unknownString:
          description: The string used as a representation for missing data.
          type: string
          example: '.'