swagger: '2.0'
paths:
  '/maps/{mapDbId}/positions/{linkageGroupName}':
    get:
      summary: Get map data by range on linkageGroup
      description: markers ordered by linkageGroup and position
      tags:
      - Genome Maps
      parameters:
        - name: mapDbId
          in: path
          description: unique id of the map
          required: true
          type: string
        - name: linkageGroupName
          in: path
          description: >-
            The chromosome identifier or the generic linkage group identifier if
            the chromosome is not applicable.
          required: true
          type: string
        - name: min
          in: query
          description: minimum position on linkage group
          required: false
          type: integer
        - name: max
          in: query
          description: maximum position on linkage group
          required: false
          type: integer
        - name: type
          in: query
          description: The type of the marker.
          required: false
          type: string
        - name: pageSize
          in: query
          description: The size of the pages to be returned. Default is `1000`.
          required: false
          type: integer
        - name: page
          in: query
          description: >-
            Which result page is requested. The page indexing starts at 0 (the
            first page is 'page'= 0). Default is `0`.
          required: false
          type: integer
      produces:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            title: markersResponse
            type: object
            properties:
              metadata:
               $ref: '#/definitions/metadata'
              result:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/definitions/markerSummaryMap'
          headers: {}
          examples:
            application/json:
              metadata:
                pagination:
                  pageSize: 1000
                  currentPage: 0
                  totalCount: 2
                  totalPages: 1
                status: []
                datafiles: []
              result:
                data:
                  - markerDbId: '1185'
                    markerName: '11_10002'
                    position: '1000'
                    linkageGroupName: 1A
                    type: SNP
                    synonyms:
                      - i_11_10002
                      - POPA1_0002
                    refAlt:
                      - A
                      - T
                    analysisMethods:
                      - illumina
                      - kasp
                  - markerDbId: '1186'
                    markerName: '11_11159'
                    position: '1100'
                    linkageGroupName: 1A
                    type: SNP
                    synonyms:
                      - i_11_11159
                      - POPA1_1159
                    refAlt:
                      - A
                      - T
                    analysisMethods:
                      - illumina
                      - kasp