info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths:
  /events:
    get:
      summary: Get the Events
      description: Get list of events
      parameters:
      - description: Filter based on an ObservationUnit unique identifier in which the events occurred
        in: query
        name: observationUnitDbId
        required: false
        schema:
          type: string
      - description: Filter based on an Event DbId
        in: query
        name: eventDbId
        required: false
        schema:
          type: string
      - description: Filter based on an Event Type
        in: query
        name: eventType
        required: false
        schema:
          type: string
      - description: Filter based on an Date Range
        in: query
        name: dateRangeStart
        required: false
        schema:
          type: string
          format: date-time
      - description: Filter based on an Date Range
        in: query
        name: dateRangeEnd
        required: false
        schema:
          type: string
          format: date-time
      - $ref: '#/components/parameters/studyDbId'
      - $ref: '#/components/parameters/page'
      - $ref: '#/components/parameters/pageSize'
      - $ref: '#/components/parameters/authorizationHeader'
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  '@context':
                    $ref: '#/components/schemas/Context'
                  metadata:
                    $ref: '#/components/schemas/metadata'
                  result:
                    properties:
                      data:
                        description: The `data` array is part of the BrAPI standard List Response JSON container. `data` will always contain the primary list of objects being returned by a BrAPI endpoint. `data` is also the only array impacted by the `metadata.pagination` details. When the pagination parameters change, the `data` array will reflect those changes in the JSON response.
                        items:
                          $ref: '#/components/schemas/Event'
                        type: array
                    required:
                    - data
                    type: object
                required:
                - metadata
                - result
                title: eventsResponse
                type: object
          description: OK
          headers: {}
        '400':
          $ref: '#/components/responses/400BadRequest'
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '403':
          $ref: '#/components/responses/403Forbidden'
      tags:
      - Events