info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths:
  /callsets/{callSetDbId}:
    get:
      summary: Gets a `CallSet` by ID.
      description: Gets a `CallSet` by ID.
      parameters:
        - name: callSetDbId
          description: The ID which uniquely identifies a `CallSet` within the given database server 
          in: path
          required: true
          schema:
            type: string
        - $ref: '#/components/parameters/authorizationHeader'
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  '@context':
                    $ref: '#/components/schemas/Context'
                  metadata:
                    $ref: '#/components/schemas/metadata'
                  result:
                    $ref: '#/components/schemas/CallSet'
                required:
                - metadata
                - result
                title: callSetResponse
                type: object
          description: OK
          headers: {}
        '400':
          $ref: '#/components/responses/400BadRequest'
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '403':
          $ref: '#/components/responses/403Forbidden'
        '404':
          $ref: '#/components/responses/404NotFound'
      tags:
        - Call Sets