info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths:
  /maps/{mapDbId}/linkagegroups:
    get:
      summary: Get the Linkage Groups of a specific Genomic Map
      description: Get the Linkage Groups of a specific Genomic Map. A Linkage Group is the BrAPI generic term for a named section of a map. A Linkage Group can represent a Chromosome, Scaffold, or Linkage Group.
      parameters:
      - description: The ID which uniquely identifies a `GenomeMap`
        in: path
        name: mapDbId
        required: true
        schema:
          type: string
      - $ref: '#/components/parameters/page'
      - $ref: '#/components/parameters/pageSize'
      - $ref: '#/components/parameters/authorizationHeader'
      responses:
        '200':
          content:
            application/json:
              schema:
                title: LinkageGroupListResponse
                type: object
                required:
                - metadata
                - result
                properties:
                  '@context':
                    $ref: '#/components/schemas/Context'
                  metadata:
                    $ref: '#/components/schemas/metadata'
                  result:
                    type: object
                    required:
                    - data
                    properties:
                      data:
                        description: The `data` array is part of the BrAPI standard List Response JSON container. `data` will always contain the primary list of objects being returned by a BrAPI endpoint. `data` is also the only array impacted by the `metadata.pagination` details. When the pagination parameters change, the `data` array will reflect those changes in the JSON response.
                        type: array
                        items:
                          $ref: '#/components/schemas/LinkageGroup'
          description: OK
          headers: {}
        '400':
          $ref: '#/components/responses/400BadRequest'
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '403':
          $ref: '#/components/responses/403Forbidden'
        '404':
          $ref: '#/components/responses/404NotFound'
      tags:
      - Genome Maps
