info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths:
  /maps/{mapDbId}:
    get:
      summary: Get the details of a specific Genomic Map
      description: Provides the number of markers on each linkageGroup and the max position on the linkageGroup
      parameters:
      - description: The ID which uniquely identifies a `GenomeMap`
        in: path
        name: mapDbId
        required: true
        schema:
          type: string
      - $ref: '#/components/parameters/authorizationHeader'
      responses:
        '200':
          content:
            application/json:
              schema:
                title: GenomeMapSingleResponse
                type: object
                required:
                - metadata
                - result
                properties:
                  '@context':
                    $ref: '#/components/schemas/Context'
                  metadata:
                    $ref: '#/components/schemas/metadata'
                  result:
                    $ref: '#/components/schemas/GenomeMap'
          description: OK
          headers: {}
        '400':
          $ref: '#/components/responses/400BadRequest'
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '403':
          $ref: '#/components/responses/403Forbidden'
        '404':
          $ref: '#/components/responses/404NotFound'
      tags:
      - Genome Maps
