info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths:
  /maps:
    get:
      summary: Get the Genomic Maps
      description: Get list of maps
      parameters:
      - name: mapDbId
        description: The ID which uniquely identifies a `GenomeMap`
        in: query
        required: false
        schema:
          type: string
      - name: mapPUI
        description: The DOI or other permanent identifier for a `GenomeMap`
        in: query
        required: false
        schema:
          type: string
      - name: scientificName
        description: Full scientific binomial format name. This includes Genus, Species, and Sub-species
        in: query
        required: false
        schema:
          type: string
      - name: type
        description: The type of map, usually "Genetic" or "Physical"
        in: query
        required: false
        schema:
          type: string
      - $ref: '#/components/parameters/commonCropName'
      - $ref: '#/components/parameters/programDbId'
      - $ref: '#/components/parameters/trialDbId'
      - $ref: '#/components/parameters/studyDbId'
      - $ref: '#/components/parameters/page'
      - $ref: '#/components/parameters/pageSize'
      - $ref: '#/components/parameters/authorizationHeader'
      responses:
        '200':
          content:
            application/json:
              schema:
                title: GenomeMapListResponse
                type: object
                required:
                - metadata
                - result
                properties:
                  '@context':
                    $ref: '#/components/schemas/Context'
                  metadata:
                    $ref: '#/components/schemas/metadata'
                  result:
                    properties:
                      data:
                        description: The `data` array is part of the BrAPI standard List Response JSON container. `data` will always contain the primary list of objects being returned by a BrAPI endpoint. `data` is also the only array impacted by the `metadata.pagination` details. When the pagination parameters change, the `data` array will reflect those changes in the JSON response.
                        items:
                          $ref: '#/components/schemas/GenomeMap'
                        type: array
                    required:
                    - data
                    type: object
          description: OK
          headers: {}
        '400':
          $ref: '#/components/responses/400BadRequest'
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '403':
          $ref: '#/components/responses/403Forbidden'
      tags:
      - Genome Maps
