info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths:
  /markerpositions: 
    get:
      summary: Get marker position info
      description: Get marker position information, based on Map, Linkage Group, and Marker ID
      parameters:
      - name: mapDbId
        description: The ID which uniquely identifies a `GenomeMap`
        in: query
        required: false
        schema:
          type: string
      - name: linkageGroupName
        description: |-
          The Uniquely Identifiable name of a `LinkageGroup`
          <br> This might be a chromosome identifier or the generic linkage group identifier if the chromosome is not applicable.
        in: query
        required: false
        schema:
          type: string
      - name: variantDbId
        description: The unique id for a marker
        in: query
        required: false
        schema:
          type: string
      - name: minPosition
        description: The minimum position 
        in: query
        required: false
        schema:
          type: integer
      - name: maxPosition
        description: The maximum position 
        in: query
        required: false
        schema:
          type: integer
      - $ref: '#/components/parameters/page'
      - $ref: '#/components/parameters/pageSize'
      - $ref: '#/components/parameters/authorizationHeader'
      responses:
        '200':
          $ref: '#/components/responses/MarkerPositionListResponse'
        '400':
          $ref: '#/components/responses/400BadRequest'
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '403':
          $ref: '#/components/responses/403Forbidden'
      tags:
      - Genome Maps
components:
  responses:
    MarkerPositionListResponse:
      content: 
        application/json: 
          schema:
            title: MarkerPositionListResponse
            type: object
            required:
            - metadata
            - result
            properties:
              '@context':
                $ref: '#/components/schemas/Context'
              metadata:
                $ref: '#/components/schemas/metadata'
              result:
                properties:
                  data:
                    description: The `data` array is part of the BrAPI standard List Response JSON container. `data` will always contain the primary list of objects being returned by a BrAPI endpoint. `data` is also the only array impacted by the `metadata.pagination` details. When the pagination parameters change, the `data` array will reflect those changes in the JSON response.
                    items:
                      $ref: '#/components/schemas/MarkerPosition'
                    type: array
                required:
                - data
                type: object
      description: OK
      headers: {}
