info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths: {}
components:
  schemas:
    Person:
      allOf:
      - $ref: '#/components/schemas/PersonNewRequest'
      - type: object
        x-brapi-metadata:
          primaryModel: true
          module: BrAPI-Core
          title: Person
          description: A generic object used to maintain the metadata needed to describe a human. The Person might be a software user, a field technician, or a primary contact for a Program.   
        required:
        - personDbId
        properties:
          personDbId:
            description: Unique ID for a person
            type: string
            example: 14340a54

