info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths:
  /germplasm/{germplasmDbId}/pedigree:
    get:
      deprecated: true
      summary:  |-
        **Deprecated in v2.1** Please use `GET /pedigree?germplasmDbId={germplasmDbId}`. Github issue number #481 
        <br/> Get the pedigree details of a specific Germplasm
      description: |-
        **Deprecated in v2.1** Please use `GET /pedigree?germplasmDbId={germplasmDbId}`. Github issue number #481 
        <br/> Get the parentage information of a specific Germplasm
      parameters:
      - description: the internal id of the germplasm
        in: path
        name: germplasmDbId
        required: true
        schema:
          type: string
      - description: text representation of the pedigree
        in: query
        name: notation
        required: false
        schema:
          type: string
      - description: include array of siblings in response
        in: query
        name: includeSiblings
        required: false
        schema:
          type: boolean
      - $ref: '#/components/parameters/authorizationHeader'
      responses:
        '200':
          content:
            application/json:
              schema:
                title: GermplasmPedigreeResponse
                type: object
                properties:
                  '@context':
                    $ref: '#/components/schemas/Context'
                  metadata:
                    $ref: '#/components/schemas/metadata'
                  result:
                    $ref: '#/components/schemas/PedigreeNodeDEP'
                required:
                - metadata
                - result
          description: OK
          headers: {}
        '400':
          $ref: '#/components/responses/400BadRequest'
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '403':
          $ref: '#/components/responses/403Forbidden'
        '404':
          $ref: '#/components/responses/404NotFound'
      tags:
      - Germplasm
