info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths: {}
components:
  schemas:
    Sample:
      allOf:
      - $ref: '#/components/schemas/SampleNewRequest'
      - type: object
        x-brapi-metadata:
          primaryModel: true
          module: BrAPI-Genotyping
          title: Sample
          description: The identifiers and metadata associated with a physical piece of biological material collected from the field for external analysis. A Sample can take many forms (leaf clipping, seed, DNA, etc) and might be used for a variety of analysis procedures (spectra, genotyping, etc). 
      required:
      - sampleDbId
      properties:
          sampleDbId:
            description: |-
              The ID which uniquely identifies a `Sample`
              <br> MIAPPE V1.1 (DM-76) Sample ID - Unique identifier for the sample.
            type: string
            example: cd06a61d

