info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths: {}
components:
  schemas:
    Location: 
      allOf:
      - $ref: '#/components/schemas/LocationNewRequest'
      - type: object
        x-brapi-metadata:
          primaryModel: true
          module: BrAPI-Core
          title: Location
          description: A geographic Location on earth. This is usually used to describe the general area where an experiment took place. For example, a natural site, an experimental field, a greenhouse, a phenotyping facility, etc. 
        properties:
          locationDbId:
            description: The unique identifier for a Location
            type: string
            example: 3cfdd67d
        required:
        - locationDbId
