info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths: {}
components:
  schemas:
    LocationNewRequest: 
      type: object
      properties: 
        abbreviation:
          description: An abbreviation which represents this location
          type: string
          example: L1
        additionalInfo:
          additionalProperties:
            type: string
          description: Additional arbitrary info
          type: object
          example: {}
        coordinateUncertainty:
          description: Uncertainty associated with the coordinates in meters. Leave the value empty if the uncertainty is unknown.
          type: string
          example: '20'
        countryCode:
          description: |-
            [ISO_3166-1_alpha-3](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-3) spec
            <br/> MIAPPE V1.1 (DM-17) Geographic location (country) - The country where the experiment took place, either as a full name or preferably as a 2-letter code.'
          type: string
          example: PER
        countryName:
          description: |-
            The full name of the country where this location is
            <br/> MIAPPE V1.1 (DM-17) Geographic location (country) - The country where the experiment took place, either as a full name or preferably as a 2-letter code.
          type: string
          example: Peru
        documentationURL:
          description: A URL to the human readable documentation of this object
          format: uri
          type: string
          example: https://brapi.org
        instituteAddress:
          description: |-
            The street address of the institute representing this location
            <br/> MIAPPE V1.1 (DM-16) Contact institution - Name and address of the institution responsible for the study.
          type: string
          example: 71 Pilgrim Avenue Chevy Chase MD 20815
        instituteName:
          description: |-
            Each institute/laboratory can have several experimental field
            <br/> MIAPPE V1.1 (DM-16) Contact institution - Name and address of the institution responsible for the study.
          type: string
          example: Plant Science Institute
        locationName:
          description: |-
            A human readable name for a location
            <br/> MIAPPE V1.1 (DM-18) Experimental site name - The name of the natural site, experimental field, greenhouse, phenotyping facility, etc. where the experiment took place.
          type: string
          example: Location 1
        parentLocationDbId:
          description: |-
            The unique identifier for a Location
            <br/> The Parent Location defines the encompassing location that this location belongs to. 
            For example, an Institution might have multiple Field Stations inside it and each Field Station might have multiple Fields.
          type: string
          example: 0a93f7d8
        parentLocationName:
          description: |-
            A human readable name for a location
            <br/> The Parent Location defines the encompassing location that this location belongs to. 
            For example, an Institution might have multiple Field Stations inside it and each Field Station might have multiple Fields.
          type: string
          example: Field Station Alpha
        locationType:
          description: The type of location this represents (ex. Field Station, Breeding Location, Storage Location, etc)
          type: string
          example: Field Station
        siteStatus:
          description: Description of the accessibility of the location (ex. Public, Private)
          type: string
          example: Private
        coordinateDescription:
          description: Describes the precision and landmarks of the coordinate values used for this location. (ex. the site, the nearest town, a 10 kilometers radius circle, +/- 20 meters, etc)
          type: string
          example: North East corner of greenhouse
        slope:
          description: Describes the approximate slope (height/distance) of the location.
          type: string
          example: '0'
        exposure:
          description: Describes the level of protection/exposure for things like sun light and wind.
          type: string
          example: Structure, no exposure
        environmentType:
          description: Describes the general type of environment of the location. (ex. forest, field, nursery, etc)
          type: string
          example: Nursery
        topography:
          description: Describes the topography of the land at the location. (ex. Plateau, Cirque, Hill, Valley, etc)
          type: string
          example: Valley
        coordinates:
          $ref: '#/components/schemas/geoJSON'
        externalReferences: 
          $ref: '#/components/schemas/ExternalReferences'
          

