info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths: {}
components:
  schemas:
    ListTypes:
      type: string
      example: germplasm
      enum:
      - germplasm
      - markers
      - variants
      - programs
      - trials
      - studies
      - observationUnits
      - observations
      - observationVariables
      - samples

