info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths:
  /drone_imagery/remove_background_save:
    post:
      summary: For removing the background using an upper and lower threshold
      description: |-
        For removing the background using an upper and lower threshold. Uses OpenCV threshold. Must be logged in to remove the background of an image via thresholding.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RemoveBackgroundSaveRequest'
      responses:
        '200':
          description: Accepted
          headers: {}
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RemoveBackgroundSaveResponse'
        '400':
          $ref: '#/components/responses/400BadRequest'
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '403':
          $ref: '#/components/responses/403Forbidden'
      tags:
      - Drone Imagery


