info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths:
  /variantsets/{variantSetDbId}/variants:
    get:
      summary: Gets a `Variants` for a given `VariantSet`.
      description: |-
        This call will return an array of `Variants`.
      parameters:
        - name: variantDbId
          description: The ID of the `Variant` to be retrieved.
          in: query
          required: false
          schema:
            type: string
        - name: variantSetDbId
          description: The ID of the `VariantSet` to be retrieved.
          in: path
          required: true
          schema:
            type: string
        - $ref: '#/components/parameters/pageToken'
        - $ref: '#/components/parameters/page'
        - $ref: '#/components/parameters/pageSize'
        - $ref: '#/components/parameters/authorizationHeader'
      responses:
        '200':
          $ref: '#/components/responses/VariantsListResponse'
        '400':
          $ref: '#/components/responses/400BadRequest'
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '403':
          $ref: '#/components/responses/403Forbidden'
      tags:
        - Variant Sets