info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths: {}
components:
  schemas:
    SearchRequestParametersPrograms: 
      type: object
      properties:
        programDbIds:
          description: |-
            A BrAPI Program represents the high level organization or group who is responsible for conducting trials and studies. Things like Breeding Programs and Funded Projects are considered BrAPI Programs. 

            Use this parameter to only return results associated with the given programs. 

            Use `GET /programs` to find the list of available programs on a server.
          items:
            type: string
          type: array
          example: ['8f5de35b', '0e2d4a13']
        programNames:
          description: |-
            Use this parameter to only return results associated with the given program names. Program names are not required to be unique.

            Use `GET /programs` to find the list of available programs on a server.
          items:
            type: string
          type: array
          example: ['Better Breeding Program', 'Best Breeding Program']
