openapi: 3.0.0
info:
  title: ga4gh/reference_service.proto
  version: version not set
paths:
  /referencesets:
    get:
      summary: Gets a list of `ReferenceSets`.
      description: Gets a filtered list of `ReferenceSets`.
      parameters:
        - name: referenceSetDbId
          description: The ID of the `ReferenceSet` to be retrieved.
          in: query
          schema:
            type: string
        - name: accession
          description: If set, return the reference sets for which the `accession` matches this string (case-sensitive, exact match).
          in: query
          schema:
            type: string
        - name: assemblyPUI
          description: If set, return the reference sets for which the `assemblyId` matches this string (case-sensitive, exact match).
          in: query
          schema:
            type: string
        - name: md5checksum
          description: If set, return the reference sets for which the `md5checksum` matches this string (case-sensitive, exact match).
          in: query
          schema:
            type: string
        - name: trialDbId
          description: The unique identifier for a Trial
          in: query
          required: false
          schema:
            type: string
        - name: studyDbId
          description: The unique identifier for a Study
          in: query
          required: false
          schema:
            type: string
        - $ref: '#/components/parameters/commonCropName'
        - $ref: '#/components/parameters/programDbId'
        - $ref: '#/components/parameters/externalReferenceId'
        - $ref: '#/components/parameters/externalReferenceSource'
        - $ref: '#/components/parameters/page'
        - $ref: '#/components/parameters/pageSize'
        - $ref: '#/components/parameters/authorizationHeader'
      responses:
        '200':
          $ref: '#/components/responses/ReferenceSetsListResponse'
        '400':
          $ref: '#/components/responses/400BadRequest'
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '403':
          $ref: '#/components/responses/403Forbidden'
      tags:
        - Reference Sets
components:
  responses:
    ReferenceSetsListResponse:
      description: OK
      headers: {}
      content:
        application/json:
          schema:
            title: ReferenceSetsListResponse
            type: object
            required:
            - metadata
            - result
            properties:
              '@context':
                $ref: '#/components/schemas/Context'
              metadata:
                $ref: '#/components/schemas/metadata'
              result:
                title: ReferenceSetsListResponseResult
                type: object
                required:
                - data
                properties:
                  data:
                    items:
                      $ref: '#/components/schemas/ReferenceSet'
                    type: array