info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths: {}
components:
  schemas:
    Season: 
      type: object
      x-brapi-metadata:
        primaryModel: true
        module: BrAPI-Core
        title: Season
        description: A Season defines a period in time. A Season is made of two parts; (1) the primary year and (2) a term which defines a segment of the year. This term could be a traditional season, like "Spring" or "Summer", or this term could be a month, like "May" or "June", or this could be an arbitrary season name which is meaningful to the breeding Program like "PlantingTime_3" or "Season E".
      required:
      - seasonDbId
      properties:
        seasonName:
          description: Name of the season. ex. 'Spring', 'Q2', 'Season A', etc.
          type: string
          example: Spring
        seasonDbId:
          description: The ID which uniquely identifies a season. For backward compatibility it can be a string like '2012', '1957-2004'
          type: string
          example: Spring_2018
        year:
          description: The 4 digit year of the season.
          type: integer
          example: 2018

