info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths:
  /drone_imagery/calculate_vegetative_index:
    post:
      summary: For calculating a vegetation index for an image.
      description: |-
        For calculating a vegetation index for an image. The input image is a 3 channel image, such as BGR (Blue, Green, Red) or 
        NRN (NIR, Red, NIR). The vegetation index is saved as an image in the database and returned. Must be logged in to merge drone run band images.

        Replace `POST /drone_imagery/calculate_vegetative_index` with `POST /imagemutationruns` with the following example JSON

        ```
        {
          "imageMutationDbId": "224ab7d3",
          "imagingEventDbId": "32aa577d",
          "imageMutationParameters": [
            {
              "parameterName": "vegetative_index",
              "parameterValue": "NDVI"
            },{
              "parameterName": "image_type",
              "parameterValue": "NRN"
            }
          ],
          "inputImageCollectionDbIds": [],
          "inputImageDbIds": [
            "34a22db7"
          ]
        }
        ``` 
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CalculateVegetativeIndexRequest'
      responses:
        '200':
          description: Accepted
          headers: {}
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CalculateVegetativeIndexResponse'
        '400':
          $ref: '#/components/responses/400BadRequest'
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '403':
          $ref: '#/components/responses/403Forbidden'
      tags:
      - Drone Imagery


