info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths: {}
components:
  parameters:
    germplasmDbId:
      name: germplasmDbId
      description: |-
        Use this parameter to only return results associated with the given `Germplasm` unique identifier. 
        <br/>Use `GET /germplasm` to find the list of available `Germplasm` on a server.
      in: query
      required: false
      schema:
        type: string
    germplasmName:
      name: germplasmName
      description: |-
        Use this parameter to only return results associated with the given `Germplasm` by its human readable name. 
        <br/>Use `GET /germplasm` to find the list of available `Germplasm` on a server.
      in: query
      required: false
      schema:
        type: string
    germplasmPUI:
      name: germplasmPUI
      description: |-
        Use this parameter to only return results associated with the given `Germplasm` by its global permanent unique identifier. 
        <br/>Use `GET /germplasm` to find the list of available `Germplasm` on a server.
      in: query
      required: false
      schema:
        type: string