info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths: {}
components:
  parameters:
    methodDbId:
      name: methodDbId
      description: Method unique identifier
      in: query
      required: false
      schema:
        type: string
    methodName:
      name: methodName
      description: |-
            Human readable name for the method
            <br/>MIAPPE V1.1 (DM-88) Method  Name of the method of observation
      in: query
      required: false
      schema:
        type: string
    methodPUI:
      name: methodPUI
      description: The Permanent Unique Identifier of a Method, usually in the form of a URI
      in: query
      required: false
      schema:
        type: string
    scaleDbId:
      name: scaleDbId
      description: Scale unique identifier
      in: query
      required: false
      schema:
        type: string
    scaleName:
      name: scaleName
      description: |-
            Human readable name for the scale
            <br/>MIAPPE V1.1 (DM-88) Scale  Name of the scale of observation
      in: query
      required: false
      schema:
        type: string
    scalePUI:
      name: scalePUI
      description: The Permanent Unique Identifier of a Scale, usually in the form of a URI
      in: query
      required: false
      schema:
        type: string
    traitDbId:
      name: traitDbId
      description: Trait unique identifier
      in: query
      required: false
      schema:
        type: string
    traitName:
      name: traitName
      description: |-
            Human readable name for the trait
            <br/>MIAPPE V1.1 (DM-88) Trait  Name of the trait of observation
      in: query
      required: false
      schema:
        type: string
    traitPUI:
      name: traitPUI
      description: The Permanent Unique Identifier of a Trait, usually in the form of a URI
      in: query
      required: false
      schema:
        type: string

