info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths:
  /lists:
    get:
      summary: Get filtered set of generic lists
      description: Get filtered set of generic lists
      parameters:
      - description: A flag to indicate the type of objects that are referenced in a List 
        in: query
        name: listType
        required: false
        schema:
          $ref: '#/components/schemas/ListTypes'
      - description: The human readable name of a List
        in: query
        name: listName
        required: false
        schema:
          type: string
      - description: The unique identifier of a List
        in: query
        name: listDbId
        required: false
        schema:
          type: string
      - description: A short tag to indicate the source of a list
        in: query
        name: listSource
        required: false
        schema:
          type: string
      - $ref: '#/components/parameters/commonCropName'
      - $ref: '#/components/parameters/programDbId'
      - $ref: '#/components/parameters/externalReferenceID'
      - $ref: '#/components/parameters/externalReferenceId'
      - $ref: '#/components/parameters/externalReferenceSource'
      - $ref: '#/components/parameters/page'
      - $ref: '#/components/parameters/pageSize'
      - $ref: '#/components/parameters/authorizationHeader'
      responses:
        '200':
          $ref: '#/components/responses/ListsListResponse'
        '400':
          $ref: '#/components/responses/400BadRequest'
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '403':
          $ref: '#/components/responses/403Forbidden'
      tags:
      - Lists
    post:
      summary: Create New List Objects
      description: Create new list objects in the database
      parameters:
      - $ref: '#/components/parameters/authorizationHeader'
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/ListNewRequest'
      responses:
        '200':
          $ref: '#/components/responses/ListsListResponse'
        '400':
          $ref: '#/components/responses/400BadRequest'
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '403':
          $ref: '#/components/responses/403Forbidden'
      tags:
      - Lists
components:
  responses:
    ListsListResponse:
      content:
        application/json:
          schema:
            title: ListsListResponse
            properties:
              '@context':
                $ref: '#/components/schemas/Context'
              metadata:
                $ref: '#/components/schemas/metadata'
              result:
                type: object
                properties:
                  data:
                    description: The `data` array is part of the BrAPI standard List Response JSON container. `data` will always contain the primary list of objects being returned by a BrAPI endpoint. `data` is also the only array impacted by the `metadata.pagination` details. When the pagination parameters change, the `data` array will reflect those changes in the JSON response.
                    type: array
                    items:
                      $ref: '#/components/schemas/ListSummary'
                required:
                - data
            required:
            - metadata
            - result
            type: object
      description: OK
      headers: {}
    
