info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths: {}
components:
  schemas:
    NIRSProtocolNewRequest:
      type: object
      properties:
        additionalInfo:
          additionalProperties:
            type: string
          description: Additional arbitrary info
          type: object
        externalReferences: 
          $ref: '#/components/schemas/ExternalReferences'
        documentationURL:
          description: description
          format: uri
          type: string
          example: https://wiki.brapi.org
        deviceType:
          description: description
          type: string
          example: SCIO
        header_column_names:
          description: description
          type: array
          example: [740, 742, 744, 746]
          items:
            type: integer

          

