info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths: {}
components:
  schemas:
    CrossingProject:
      allOf:
        - $ref: '#/components/schemas/CrossingProjectNewRequest'
        - type: object
          x-brapi-metadata:
            primaryModel: true
            module: BrAPI-Germplasm
            title: CrossingProject
            description: A project structure where a list of PlannedCrosses is generated, the crossing events occur in the field, and the resulting actual Crosses can documented. 
          required:
          - crossingProjectDbId
          properties:
            crossingProjectDbId:
              description: The unique identifier for a crossing project
              type: string
              example: ce0e1c29