info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths:
  /calls:
    get:
      summary: Gets a filtered list of `Calls`
      description: |-
        Gets a filtered list of `Call` JSON objects.
      parameters:
        - name: callSetDbId
          description: The ID which uniquely identifies a `CallSet` within the given database server 
          in: query
          required: false
          schema:
            type: string
        - name: variantDbId
          description: The ID which uniquely identifies a `Variant` within the given database server 
          in: query
          required: false
          schema:
            type: string
        - name: variantSetDbId
          description: The ID which uniquely identifies a `VariantSet` within the given database server 
          in: query
          required: false
          schema:
            type: string
        - name: expandHomozygotes
          description: Should homozygotes be expanded (true) or collapsed into a single occurrence (false)
          in: query
          required: false
          schema:
            type: boolean
        - name: unknownString
          description: The string to use as a representation for missing data
          in: query
          required: false
          schema:
            type: string
        - name: sepPhased
          description: The string to use as a separator for phased allele calls
          in: query
          required: false
          schema:
            type: string
        - name: sepUnphased
          description: The string to use as a separator for unphased allele calls
          in: query
          required: false
          schema:
            type: string
        - $ref: '#/components/parameters/pageToken'
        - $ref: '#/components/parameters/page'
        - $ref: '#/components/parameters/pageSize'
        - $ref: '#/components/parameters/authorizationHeader'
      responses:
        '200':
          $ref: '#/components/responses/CallsListResponse'
        '400':
          $ref: '#/components/responses/400BadRequest'
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '403':
          $ref: '#/components/responses/403Forbidden'
      tags:
        - Calls
    put:
      summary: Update existing `Calls` with new genotype value or metadata 
      description: |-
        Update existing `Calls` with new genotype value or metadata
        <br/>Implementation Note - 
        <br/>A `Call` object does not have a DbId of its own. It is defined by the unique combination of 
        `callSetDbId`, `variantDbId`, and `variantSetDbId`. These three fields MUST be present for every 
        `call` update request. This endpoint should not allow these fields to be modified for a given 
        `call`. Modifying these fields in the database is effectively moving a cell to a different location
        in the genotype matrix. This action is dangerous and can cause data collisions.     
      parameters:
        - $ref: '#/components/parameters/authorizationHeader'
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Call'
      responses:
        '200':
          $ref: '#/components/responses/CallsListResponse'
        '400':
          $ref: '#/components/responses/400BadRequest'
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '403':
          $ref: '#/components/responses/403Forbidden'
      tags:
        - Calls