info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths: {}
components:
  schemas:
    GermplasmMCPD:
      properties:
        accessionNames:
          description: MCPD (v2.1) (ACCENAME) 11. A collection of either a registered names or other designations given to the material received, other than the donors accession number (23) or collecting number (3). First letter uppercase.
          items:
            type: string
          type: array
          example: ['Symphony', 'Emma']
        accessionNumber:
          description: |- 
            The unique identifier for a material or germplasm within a genebank

            MCPD (v2.1) (ACCENUMB) 2. This is the unique identifier for accessions within a genebank, and is assigned when a sample is entered into the genebank collection (e.g. "PI 113869").
          type: string
          example: A0000003
        acquisitionDate:
          description: |-
            The date a material or germplasm was acquired by the genebank 
            
            MCPD (v2.1) (ACQDATE) 12. Date on which the accession entered the collection [YYYYMMDD] where YYYY is the year, MM is the month and DD is the day. Missing data (MM or DD) should be indicated with hyphens or "00" [double zero].
          type: string
          format: date
        acquisitionSourceCode:
          description: |-
            MCPD (v2.1) (COLLSRC) 21. The coding scheme proposed can be used at 2 different levels of detail: either by using the general codes (in bold-face) such as 10, 20, 30, 40, etc., or by using the more specific codes, such as 11, 12, etc. 
            
            10) Wild habitat 
            11) Forest or woodland 
            12) Shrubland 
            13) Grassland 
            14) Desert or tundra 
            15) Aquatic habitat 
            20) Farm or cultivated habitat 
            21) Field 
            22) Orchard 
            23) Backyard, kitchen or home garden (urban, peri-urban or rural) 
            24) Fallow land 
            25) Pasture 
            26) Farm store 
            27) Threshing floor 
            28) Park 
            30) Market or shop 
            40) Institute, Experimental station, Research organization, Genebank 
            50) Seed company 
            60) Weedy, disturbed or ruderal habitat 
            61) Roadside 
            62) Field margin 
            99) Other (Elaborate in REMARKS field)
          enum: ['10', '11', '12', '13', '14', '15', '20', '21', '22', '23', '24', '25', '26', '27', '28', '30', '40', '50', '60', '61', '62', '99']
          type: string
          example: '26'
        alternateIDs:
          description: 'MCPD (v2.1) (OTHERNUMB) 24. Any other identifiers known to exist in other collections for this accession. Use the following format: INSTCODE:ACCENUMB;INSTCODE:identifier;INSTCODE and identifier are separated by a colon without space. Pairs of INSTCODE and identifier are separated by a semicolon without space. When the institute is not known, the identifier should be preceded by a colon. '
          items:
            type: string
          type: array
          example: ['PER001:3', 'PER001:http://pui.per/accession/A0000003', 'USA001:A0000003']
        ancestralData:
          description: MCPD (v2.1) (ANCEST) 20. Information about either pedigree or other description of ancestral information (e.g. parent variety in case of mutant or selection). For example a pedigree 'Hanna/7*Atlas//Turk/8*Atlas' or a description 'mutation found in Hanna', 'selection from Irene' or 'cross involving amongst others Hanna and Irene'.
          type: string
          example: A0000001/A0000002
        biologicalStatusOfAccessionCode:
          description: |-
            MCPD (v2.1) (SAMPSTAT) 19. The coding scheme proposed can be used at 3 different levels of detail: either by using the general codes such as 100, 200, 300, 400, or by using the more specific codes such as 110, 120, etc. 
            
            100) Wild 
            110) Natural 
            120) Semi-natural/wild 
            130) Semi-natural/sown 
            200) Weedy 
            300) Traditional cultivar/landrace 
            400) Breeding/research material 
            410) Breeders line 
            411) Synthetic population 
            412) Hybrid 
            413) Founder stock/base population 
            414) Inbred line (parent of hybrid cultivar) 
            415) Segregating population 
            416) Clonal selection 
            420) Genetic stock 
            421) Mutant (e.g. induced/insertion mutants, tilling populations) 
            422) Cytogenetic stocks (e.g. chromosome addition/substitution, aneuploids,  amphiploids) 
            423) Other genetic stocks (e.g. mapping populations) 
            500) Advanced or improved cultivar (conventional breeding methods) 
            600) GMO (by genetic engineering) 
            999) Other (Elaborate in REMARKS field)
          enum: [ '100', '110', '120', '130', '200', '300', '400', '410', '411', '412', '413', '414', '415', '416', '420', '421', '422', '423', '500', '600', '999']
          type: string
          example: '421'
        breedingInstitutes:
          description: |-
            A list of institutes that were involved with breeding a material/germplasm
            <br> MCPD (v2.1) (BREDCODE) 18. FAO WIEWS code of the institute that has bred the material. If the holding institute has bred the material, the breeding institute code (BREDCODE) should be the same as the holding institute code (INSTCODE). Follows INSTCODE standard.
            <br> MCPD (v2.1) (BREDNAME) 18.1  Name of the institute (or person) that bred the material. This descriptor should be used only if BREDCODE can not be filled because the FAO WIEWS code for this institute is not available.
          type: array
          items:
            type: object
            properties:
              instituteCode:
                description: MCPD (v2.1) (BREDCODE) 18. FAO WIEWS code of the institute that has bred the material. If the holding institute has bred the material, the breeding institute code (BREDCODE) should be the same as the holding institute code (INSTCODE). Follows INSTCODE standard.
                type: string
                example: PER001
              instituteName:
                description: MCPD (v2.1) (BREDNAME) 18.1  Name of the institute (or person) that bred the material. This descriptor should be used only if BREDCODE can not be filled because the FAO WIEWS code for this institute is not available.
                type: string
                example: The BrAPI Institute
        collectingInfo:
          description: Information about the collection of a germplasm
          properties:
            collectingDate:
              description: MCPD (v2.1) (COLLDATE) 17. Collecting date of the sample [YYYYMMDD] where YYYY is the year, MM is the month and DD is the day. Missing data (MM or DD) should be indicated with hyphens or "00" [double zero].
              type: string
              format: date
            collectingInstitutes:
              description: Institutes which collected the sample
              type: array
              items:
                type: object
                properties:
                  instituteAddress:
                    description: MCPD (v2.1) (COLLINSTADDRESS) 4.1.1  Address of the institute collecting the sample. This descriptor should be used only if COLLCODE can not be filled since the FAO WIEWS code for this institute is not available. Multiple values are separated by a semicolon without space.
                    type: string
                    example: 123 Main Street, Lima, Peru, 5555
                  instituteCode:
                    description: MCPD (v2.1) (COLLCODE) 4.  FAO WIEWS code of the institute collecting the sample. If the holding institute has collected the material, the collecting institute code (COLLCODE) should be the same as the holding institute code (INSTCODE). Follows INSTCODE standard. Multiple values are separated by a semicolon without space.
                    type: string
                    example: PER001
                  instituteName:
                    description: MCPD (v2.1) (COLLNAME) 4.1  Name of the institute collecting the sample. This descriptor should be used only if COLLCODE can not be filled because the FAO WIEWS code for this institute is not available. Multiple values are separated by a semicolon without space.
                    type: string
                    example: The BrAPI Institute
            collectingMissionIdentifier:
              description: MCPD (v2.1) (COLLMISSID) 4.2 Identifier of the collecting mission used by the Collecting Institute (4 or 4.1) (e.g. "CIATFOR_052", "CN_426").
              type: string
              example: 'CIATFOR_052'
            collectingNumber:
              description: MCPD (v2.1) (COLLNUMB) 3. Original identifier assigned by the collector(s) of the sample, normally composed of the name or initials of the collector(s) followed by a number (e.g. "ab109909"). This identifier is essential for identifying duplicates held in different collections.
              type: string
              example: ab109909
            collectingSite:
              description: Information about the location where the sample was collected
              properties:
                coordinateUncertainty:
                  description: MCPD (v2.1) (COORDUNCERT) 15.5 Uncertainty associated with the coordinates in metres. Leave the value empty if the uncertainty is unknown.
                  type: string
                  example: '20'
                elevation:
                  description: MCPD (v2.1) (ELEVATION) 16. Elevation of collecting site expressed in metres above sea level. Negative values are allowed.
                  type: string
                  example: '35'
                georeferencingMethod:
                  description: MCPD (v2.1) (GEOREFMETH) 15.7  The georeferencing method used (GPS, determined from map, gazetteer, or estimated using software). Leave the value empty if georeferencing method is not known.
                  type: string
                  example: WGS84
                latitudeDecimal:
                  description: MCPD (v2.1) (DECLATITUDE) 15.1 Latitude expressed in decimal degrees. Positive values are North of the Equator; negative values are South of the Equator (e.g. -44.6975).
                  type: string
                  example: '+42.445295'
                latitudeDegrees:
                  description: MCPD (v2.1) (LATITUDE) 15.2 Degrees (2 digits) minutes (2 digits), and seconds (2 digits) followed by N (North) or S (South) (e.g. 103020S). Every missing digit (minutes or seconds) should be indicated with a hyphen. Leading zeros are required (e.g. 10
                  type: string
                  example: '42 26 43.1 N'
                locationDescription:
                  description: MCPD (v2.1) (COLLSITE) 14. Location information below the country level that describes where the accession was collected, preferable in English. This might include the distance in kilometres and direction from the nearest town, village or map grid reference point, (e.g. 7 km south of Townsville).
                  type: string
                  example: South east hill near institute buildings
                longitudeDecimal:
                  description: MCPD (v2.1) (DECLONGITUDE) 15.3 Longitude expressed in decimal degrees. Positive values are East of the Greenwich Meridian; negative values are West of the Greenwich Meridian (e.g. +120.9123).
                  type: string
                  example: '-076.471934'
                longitudeDegrees:
                  description: MCPD (v2.1) (LONGITUDE) 15.4 Degrees (3 digits), minutes (2 digits), and seconds (2 digits) followed by E (East) or W (West) (e.g. 0762510W). Every missing digit (minutes or seconds) should be indicated with a hyphen. Leading zeros are required (e.g. 076
                  type: string
                  example: '76 28 19.0 W'
                spatialReferenceSystem:
                  description: MCPD (v2.1) (COORDDATUM) 15.6 The geodetic datum or spatial reference system upon which the coordinates given in decimal latitude and decimal longitude are based (e.g. WGS84). The GPS uses the WGS84 datum.
                  type: string
                  example: WGS84
              type: object
          type: object
        commonCropName:
          description: 'MCPD (v2.1) (CROPNAME) 10. Common name of the crop. Example: "malting barley", "mas". '
          type: string
          example: malting barley
        countryOfOrigin:
          description: 'MCPD (v2.1) (ORIGCTY) 13. 3-letter ISO 3166-1 code of the country in which the sample was originally collected (e.g. landrace, crop wild relative, farmers" variety), bred or selected (breeding lines, GMOs, segregating populations, hybrids, modern cultivars, etc.). Note: Descriptors 14 to 16 below should be completed accordingly only if it was "collected".'
          type: string
          example: Peru
        donorInfo:
          type: object
          description: Information about an accession donor
          properties:
            donorAccessionPui:
              description: PUI (DOI mostly) of the accession in the donor system.
              type: string
              example: http://pui.per/accession/A0010025
            donorAccessionNumber:
              description: MCPD (v2.1) (DONORNUMB) 23. Identifier assigned to an accession by the donor. Follows ACCENUMB standard.
              type: string
              example: A0090204
            donorInstitute:
              description: |-
                The identifying information for the entity acting as an accession donor
                <br> MCPD (v2.1) (DONORCODE) 22. FAO WIEWS code of the donor institute. Follows INSTCODE standard.
                <br> MCPD (v2.1) (DONORNAME) 22.1  Name of the donor institute (or person). This descriptor should be used only if DONORCODE can not be filled because the FAO WIEWS code for this institute is not available.
              type: object
              properties:
                instituteCode:
                  description: MCPD (v2.1) (DONORCODE) 22. FAO WIEWS code of the donor institute. Follows INSTCODE standard.
                  type: string
                  example: PER001
                instituteName:
                  description: MCPD (v2.1) (DONORNAME) 22.1  Name of the donor institute (or person). This descriptor should be used only if DONORCODE can not be filled because the FAO WIEWS code for this institute is not available.
                  type: string
                  example: The BrAPI Institute
        genus:
          description: MCPD (v2.1) (GENUS) 5. Genus name for taxon. Initial uppercase letter required.
          type: string
          example: Aspergillus
        germplasmDbId:
          description: A unique identifier which identifies a germplasm in this database
          type: string
          example: 31c4efbc
        germplasmPUI:
          description: MCPD (v2.1) (PUID) 0. Any persistent, unique identifier assigned to the accession so it can be unambiguously referenced at the global level and the information associated with it harvested through automated means. Report one PUID for each accession. The Secretariat of the International Treaty on Plant Genetic Resources for Food and Agriculture (PGRFA) is facilitating the assignment of a persistent unique identifier (PUID), in the form of a DOI, to PGRFA at the accession level. Genebanks not applying a true PUID to their accessions should use, and request recipients to use, the concatenation of INSTCODE, ACCENUMB, and GENUS as a globally unique identifier similar in most respects to the PUID whenever they exchange information on accessions with third parties.
          type: string
          example: http://pui.per/accession/A0403652
        instituteCode:
          description: MCPD (v2.1) (INSTCODE) 1. FAO WIEWS code of the institute where the accession is maintained. The codes consist of the 3-letter ISO 3166 country code of the country where the institute is located plus a number (e.g. PER001). The current set of institute codes is available from http://www.fao.org/wiews. For those institutes not yet having an FAO Code, or for those with "obsolete" codes, see "Common formatting rules (v)".
          type: string
          example: PER001
        mlsStatus:
          description: MCPD (v2.1) (MLSSTAT) 27. The status of an accession with regards to the Multilateral System (MLS) of the International Treaty on Plant Genetic Resources for Food and Agriculture. Leave the value empty if the status is not known 0 No (not included) 1 Yes (included) 99 Other (elaborate in REMARKS field, e.g. "under development")
          enum:
          - ''
          - '0'
          - '1'
          - '99'
          type: string
          example: '0'
        remarks:
          description: MCPD (v2.1) (REMARKS) 28. The remarks field is used to add notes or to elaborate on descriptors with value 99 or 999 (= Other). Prefix remarks with the field name they refer to and a colon (:) without space (e.g. COLLSRC:riverside). Distinct remarks referring to different fields are separated by semi-colons without space.
          type: string
          example: This is an example remark to demonstrate that any notable information can be put here
        safetyDuplicateInstitutes:
          items:
            properties:
              instituteCode:
                description: MCPD (v2.1) (DUPLSITE) 25. FAO WIEWS code of the institute(s) where a safety duplicate of the accession is maintained. Follows INSTCODE standard.
                type: string
                example: PER001
              instituteName:
                description: MCPD (v2.1) (DUPLINSTNAME) 25.1  Name of the institute where a safety duplicate of the accession is maintained.
                type: string
                example: The BrAPI Institute
            type: object
          type: array
        species:
          description: 'MCPD (v2.1) (SPECIES) 6. Specific epithet portion of the scientific name in lowercase letters. Only the following abbreviation is allowed: "sp." '
          type: string
          example: fructus
        speciesAuthority:
          description: MCPD (v2.1) (SPAUTHOR) 7. Provide the authority for the species name.
          type: string
          example: Smith, 1822
        storageTypeCodes:
          description: MCPD (v2.1) (STORAGE) 26. If germplasm is maintained under different types of storage, multiple choices are allowed, separated by a semicolon (e.g. 20;30). (Refer to FAO/IPGRI Genebank Standards 1994 for details on storage type.) 10) Seed collection 11) Short term 12) Medium term 13) Long term 20) Field collection 30) In vitro collection 40) Cryo-preserved collection 50) DNA collection 99) Other (elaborate in REMARKS field)
          items:
            enum:
            - '10'
            - '11'
            - '12'
            - '13'
            - '20'
            - '30'
            - '40'
            - '50'
            - '99'
            type: string
          type: array
          example: ['11', '13']
        subtaxon:
          description: 'MCPD (v2.1) (SUBTAXA) 8. Subtaxon can be used to store any additional taxonomic identifier. The following abbreviations are allowed: "subsp." (for subspecies); "convar." (for convariety); "var." (for variety); "f." (for form); "Group" (for "cultivar group").'
          type: string
          example: Aspergillus fructus A
        subtaxonAuthority:
          description: MCPD (v2.1) (SUBTAUTHOR) 9. Provide the subtaxon authority at the most detailed taxonomic level.
          type: string
          example: Smith, 1822
      type: object

