info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths: {}
components:
  schemas:
    GermplasmNewRequest:
      type: object
      required:
      - commonCropName
      - germplasmName
      - germplasmPUI
      properties:
        additionalInfo:
          additionalProperties:
            type: string
          description: A free space containing any additional information related to a particular object. A data source may provide any JSON object, unrestricted by the BrAPI specification.
          type: object
        accessionNumber:
          description: |- 
            The unique identifier for a material or germplasm within a genebank

            MCPD (v2.1) (ACCENUMB) 2. This is the unique identifier for accessions within a genebank, and is assigned when a sample is entered into the genebank collection (e.g. "PI 113869").
          type: string
          example: A0000003
        acquisitionDate:
          description: |-
            The date a material or germplasm was acquired by the genebank 
            
            MCPD (v2.1) (ACQDATE) 12. Date on which the accession entered the collection [YYYYMMDD] where YYYY is the year, MM is the month and DD is the day. Missing data (MM or DD) should be indicated with hyphens or "00" [double zero].
          format: date
          type: string
        biologicalStatusOfAccessionCode:
          description: |-
            MCPD (v2.1) (SAMPSTAT) 19. The coding scheme proposed can be used at 3 different levels of detail: either by using the general codes such as 100, 200, 300, 400, or by using the more specific codes such as 110, 120, etc. 
            
            100) Wild 
            110) Natural 
            120) Semi-natural/wild 
            130) Semi-natural/sown 
            200) Weedy 
            300) Traditional cultivar/landrace 
            400) Breeding/research material 
            410) Breeders line 
            411) Synthetic population 
            412) Hybrid 
            413) Founder stock/base population 
            414) Inbred line (parent of hybrid cultivar) 
            415) Segregating population 
            416) Clonal selection 
            420) Genetic stock 
            421) Mutant (e.g. induced/insertion mutants, tilling populations) 
            422) Cytogenetic stocks (e.g. chromosome addition/substitution, aneuploids,  amphiploids) 
            423) Other genetic stocks (e.g. mapping populations) 
            500) Advanced or improved cultivar (conventional breeding methods) 
            600) GMO (by genetic engineering) 
            999) Other (Elaborate in REMARKS field)
          enum: [ '100', '110', '120', '130', '200', '300', '400', '410', '411', '412', '413', '414', '415', '416', '420', '421', '422', '423', '500', '600', '999']
          type: string
          example: '420'
        biologicalStatusOfAccessionDescription:
          description: Supplemental text description for 'biologicalStatusOfAccessionCode'
          type: string
          example: 'Genetic stock'
        breedingMethodDbId:
          description: The unique identifier for the breeding method used to create this germplasm
          type: string
          example: ffcce7ef
        breedingMethodName:
          description: human readable name of the breeding method
          type: string
          example: Male Backcross
        collection:
          description: A specific panel/collection/population name this germplasm belongs to.
          type: string
          example: Rice Diversity Panel 1 (RDP1)
        commonCropName:
          description: |-
            Common name for the crop 
            
            MCPD (v2.1) (CROPNAME) 10. Common name of the crop. Example: "malting barley", "mas".
          type: string
          example: Maize
        countryOfOriginCode:
          description: |-
            3-letter ISO 3166-1 code of the country in which the sample was originally collected 
            
            MCPD (v2.1) (ORIGCTY) 13. 3-letter ISO 3166-1 code of the country in which the sample was originally collected (e.g. landrace, crop wild relative, farmers variety), bred or selected (breeding lines, GMOs, segregating populations, hybrids, modern cultivars, etc.). Note- Descriptors 14 to 16 below should be completed accordingly only if it was "collected".
          type: string
          example: BES
        defaultDisplayName:
          description: Human readable name used for display purposes
          type: string
          example: A0000003
        documentationURL:
          description: A URL to the human readable documentation of an object
          format: uri
          type: string
          example: https://wiki.brapi.org
        donors:
          description: List of donor institutes
          items:
            properties:
              donorAccessionNumber:
                description: |-
                  The accession number assigned by the donor
                                                
                  MCPD (v2.1) (DONORNUMB) 23. Identifier assigned to an accession by the donor. Follows ACCENUMB standard.
                type: string
                example: A0000123
              donorInstituteCode:
                description: |-
                  The institute code for the donor institute
                  <br/>MCPD (v2.1) (DONORCODE) 22. FAO WIEWS code of the donor institute. Follows INSTCODE standard.
                type: string
                example: PER001
            type: object
          type: array
        genus:
          description: |-
            Genus name for taxon. Initial uppercase letter required.
            
            MCPD (v2.1) (GENUS) 5. Genus name for taxon. Initial uppercase letter required.
            
            MIAPPE V1.1 (DM-43) Genus - Genus name for the organism under study, according to standard scientific nomenclature.
          type: string
          example: Aspergillus
        germplasmName:
          description: |-
            Name of the germplasm. It can be the preferred name and does not have to be unique.
            
            MCPD (v2.1) (ACCENAME) 11. Either a registered or other designation given to the material received, other than the donors accession number (23) or collecting number (3). First letter uppercase. Multiple names are separated by a semicolon without space.
          type: string
          example: A0000003
        germplasmPUI:
          description: |-
            The Permanent Unique Identifier which represents a germplasm
            
            MIAPPE V1.1 (DM-41) Biological material ID - Code used to identify the biological material in the data file. Should be unique within the Investigation. Can correspond to experimental plant ID, seed lot ID, etc This material identification is different from a BiosampleID which corresponds to Observation Unit or Samples sections below.
            
            MIAPPE V1.1 (DM-51) Material source DOI - Digital Object Identifier (DOI) of the material source

            MCPD (v2.1) (PUID) 0. Any persistent, unique identifier assigned to the accession so it can be unambiguously referenced at the global level and the information associated with it harvested through automated means. Report one PUID for each accession. The Secretariat of the International Treaty on Plant Genetic Resources for Food and Agriculture (PGRFA) is facilitating the assignment of a persistent unique identifier (PUID), in the form of a DOI, to PGRFA at the accession level. Genebanks not applying a true PUID to their accessions should use, and request recipients to use, the concatenation of INSTCODE, ACCENUMB, and GENUS as a globally unique identifier similar in most respects to the PUID whenever they exchange information on accessions with third parties.
          type: string
          example: http://pui.per/accession/A0000003
        species:
          description: |-
            Specific epithet portion of the scientific name in lowercase letters.
            
            MCPD (v2.1) (SPECIES) 6. Specific epithet portion of the scientific name in lowercase letters. Only the following abbreviation is allowed: "sp." 
            
            MIAPPE V1.1 (DM-44) Species - Species name (formally: specific epithet) for the organism under study, according to standard scientific nomenclature.
          type: string
          example: fructus
        instituteCode:
          description: |-
            The code for the institute that maintains the material. 
            
            MCPD (v2.1) (INSTCODE) 1. FAO WIEWS code of the institute where the accession is maintained. The codes consist of the 3-letter ISO 3166 country code of the country where the institute is located plus a number (e.g. PER001). The current set of institute codes is available from http://www.fao.org/wiews. For those institutes not yet having an FAO Code, or for those with "obsolete" codes, see "Common formatting rules (v)".
          type: string
          example: PER001
        instituteName:
          description: The name of the institute that maintains the material
          type: string
          example: The BrAPI Institute
        pedigree:
          description: |-
            The cross name and optional selection history.
            
            MCPD (v2.1) (ANCEST) 20. Information about either pedigree or other description of ancestral information (e.g. parent variety in case of mutant or selection). For example a pedigree 'Hanna/7*Atlas//Turk/8*Atlas' or a description 'mutation found in Hanna', 'selection from Irene' or 'cross involving amongst others Hanna and Irene'.
          type: string
          example: A0000001/A0000002
        seedSource:
          description: |-
            An identifier for the source of the biological material
            <br/>MIAPPE V1.1 (DM-50) Material source ID (Holding institute/stock centre, accession) - An identifier for the source of the biological material, in the form of a key-value pair comprising the name/identifier of the repository from which the material was sourced plus the accession number of the repository for that material. Where an accession number has not been assigned, but the material has been derived from the crossing of known accessions, the material can be defined as follows: "mother_accession X father_accession", or, if father is unknown, as "mother_accession X UNKNOWN". For in situ material, the region of provenance may be used when an accession is not available.
          type: string
          example: INRA:095115_inra
        speciesAuthority:
          description: |-
            The authority organization responsible for tracking and maintaining the species name 
            
            MCPD (v2.1) (SPAUTHOR) 7. Provide the authority for the species name.
          type: string
          example: Smith, 1822
        subtaxa:
          description: |-
            Subtaxon can be used to store any additional taxonomic identifier.
            
            MCPD (v2.1) (SUBTAXA) 8. Subtaxon can be used to store any additional taxonomic identifier. The following abbreviations are allowed: "subsp." (for subspecies); "convar." (for convariety); "var." (for variety); "f." (for form); "Group" (for "cultivar group").
            
            MIAPPE V1.1 (DM-44) Infraspecific name - Name of any subtaxa level, including variety, crossing name, etc. It can be used to store any additional taxonomic identifier. Either free text description or key-value pair list format (the key is the name of the rank and the value is the value of  the rank). Ranks can be among the following terms: subspecies, cultivar, variety, subvariety, convariety, group, subgroup, hybrid, line, form, subform. For MCPD compliance, the following abbreviations are allowed: subsp. (subspecies); convar. (convariety); var. (variety); f. (form); Group (cultivar group).
          type: string
          example: Aspergillus fructus A
        subtaxaAuthority:
          description: |-
            The authority organization responsible for tracking and maintaining the subtaxon information
            
            MCPD (v2.1) (SUBTAUTHOR) 9. Provide the subtaxon authority at the most detailed taxonomic level.
          type: string
          example: Smith, 1822
        synonyms:
          description: |-
            List of alternative names or IDs used to reference this germplasm
            
            MCPD (v2.1) (OTHERNUMB) 24. Any other identifiers known to exist in other collections for this accession. Use the following format: INSTCODE:ACCENUMB;INSTCODE:identifier;INSTCODE and identifier are separated by a colon without space. Pairs of INSTCODE and identifier are separated by a semicolon without space. When the institute is not known, the identifier should be preceded by a colon.
          type: array
          items:
            type: object
            properties:
              synonym:
                description: Alternative name or ID used to reference this germplasm
                type: string
                example: 'variety_1'
              type:
                description: A descriptive classification for this synonym
                type: string
                example: 'Pre-Code'
        taxonIds:
          description: |-
            The list of IDs for this SPECIES from different sources. If present, NCBI Taxon should be always listed as "ncbiTaxon" preferably with a purl. The rank of this ID should be species.
            
            MIAPPE V1.1 (DM-42) Organism - An identifier for the organism at the species level. Use of the NCBI taxon ID is recommended.
          items:
            $ref: '#/components/schemas/TaxonID'
          type: array
        storageTypes:
          description: The type of storage this germplasm is kept in at a genebank.
          type: array
          example: 
            - code: '20'
              description: Field collection 
            - code: '11'
              description: Short term 
          items: 
            type: object
            properties:
              code:
                description: |-
                  The 2 digit code representing the type of storage this germplasm is kept in at a genebank. 
                  
                  MCPD (v2.1) (STORAGE) 26. If germplasm is maintained under different types of storage, multiple choices are allowed, separated by a semicolon (e.g. 20;30). (Refer to FAO/IPGRI Genebank Standards 1994 for details on storage type.) 
                  
                  10) Seed collection 
                  11) Short term 
                  12) Medium term 
                  13) Long term 
                  20) Field collection 
                  30) In vitro collection 
                  40) Cryo-preserved collection 
                  50) DNA collection 
                  99) Other (elaborate in REMARKS field)
                enum:
                - '10'
                - '11'
                - '12'
                - '13'
                - '20'
                - '30'
                - '40'
                - '50'
                - '99'
                type: string
                example: '11'
              description:
                description: A supplemental text description of the storage type
                type: string
                example: Short term 
        germplasmPreprocessing:
          description: Description of any process or treatment applied uniformly to the germplasm, prior to the study itself. Can be provided as free text or as an accession number from a suitable controlled vocabulary.
          type: string
          example: 'EO:0007210; transplanted from study 2351 observation unit ID: pot:894'
        seedSourceDescription:
          description: |-
            Description of the material source
            
            MIAPPE V1.1 (DM-56) Material source description - Description of the material source
          type: string
          example: Branches were collected from a 10-year-old tree growing in a progeny trial established in a loamy brown earth soil.
        germplasmOrigin:
          description: Information for material (orchard, natural sites, ...). Geographic identification of the plants from which seeds or cutting have been taken to produce that germplasm.
          items:
            $ref: '#/components/schemas/GermplasmOrigin'
          type: array
        externalReferences: 
          $ref: '#/components/schemas/ExternalReferences'