info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths: {}
components:
  schemas:
    ObservationUnitTable:
      type: object
      properties:
        data:
          description: The 2D matrix of observation data. ObservationVariables and other metadata are the columns, ObservationUnits are the rows.
          type: array
          items:
            type: array
            items:
              type: string
          example: 
          - ["f3a8a3db","Plant Alpha",  "0fe3e48b","2017 Plant Study","06307ec0","A0043001","76.50106681","42.44409301","2017","Field_1","Plot_11","SubPlot_111","Plant_1111","Pot_1111","Block_11","Entry_11","Rep_11","25.3","3","50.75"]
          - ["05d1b011","Plant Beta",   "0fe3e48b","2017 Plant Study","59d435cd","A0043002","76.50106683","42.44409301","2017","Field_1","Plot_11","SubPlot_112","Plant_1122","Pot_1122","Block_11","Entry_11","Rep_12","27.9","1","45.345"]
          - ["67e2d87c","Plant Gamma",  "0fe3e48b","2017 Plant Study","06307ec0","A0043001","76.50106681","42.44409356","2017","Field_1","Plot_12","SubPlot_123","Plant_1233","Pot_1233","Block_12","Entry_12","Rep_11","25.5","3","50.76"]
          - ["d98d0d4c","Plant Epsilon","0fe3e48b","2017 Plant Study","59d435cd","A0043002","76.50106683","42.44409356","2017","Field_1","Plot_12","SubPlot_124","Plant_1244","Pot_1244","Block_12","Entry_12","Rep_12","28.9","0","46.5"]
        headerRow: 
          description: |-
            <p>The table is REQUIRED to have the following columns</p>
            <ul>
              <li>observationUnitDbId - Each row is related to one Observation Unit</li>
              <li>At least one column with an observationVariableDbId</li>
            </ul>
            <p>The table may have any or all of the following OPTIONAL columns. Included columns are decided by the server developer</p>
            <ul>
              <li>observationUnitName</li>
              <li>studyDbId</li>
              <li>studyName</li>
              <li>germplasmDbId</li>
              <li>germplasmName</li>
              <li>positionCoordinateX</li>
              <li>positionCoordinateY</li>
              <li>year</li>
            </ul>
            <p>The table also may have any number of Observation Unit Hierarchy Level columns. For example:</p>
            <ul>
              <li>field</li>
              <li>plot</li>
              <li>sub-plot</li>
              <li>plant</li>
              <li>pot</li>
              <li>block</li>
              <li>entry</li>
              <li>rep</li>
            </ul>
            <p>The JSON representation provides a pair of extra arrays for defining the headers of the table. 
            The first array "headerRow" will always contain "observationUnitDbId" and any or all of the OPTIONAL column header names. 
            The second array "observationVariables" contains the names and DbIds for the Observation Variables represented in the table. 
            By appending the two arrays, you can construct the complete header row of the table. </p>
          type: array
          items:
            description: valid header fields
            type: string
            enum:
            - observationUnitDbId
            - observationUnitName
            - studyDbId
            - studyName
            - germplasmDbId
            - germplasmName
            - positionCoordinateX
            - positionCoordinateY
            - year
            - field
            - plot
            - sub-plot
            - plant
            - pot
            - block
            - entry
            - rep
          example: 
            - observationUnitDbId
            - observationUnitName
            - studyDbId
            - studyName
            - germplasmDbId
            - germplasmName
            - positionCoordinateX
            - positionCoordinateY
            - year
            - field
            - plot
            - sub-plot
            - plant
            - pot
            - block
            - entry
            - rep
        observationVariables:
          description: The list of observation variables which have values recorded for them in the data matrix. Append to the 'headerRow' for complete header row of the table.
          type: array
          items:
            type: object
            properties:
              observationVariableDbId:
                description: Variable unique identifier
                type: string
                example: 367aa1a9
              observationVariableName:
                description: Variable name (usually a short name)
                type: string
                example: Plant height
          example: 
          - observationVariableDbId: 367aa1a9 
            observationVariableName: Plant height
          - observationVariableDbId: 2acb934c 
            observationVariableName: Carotenoid
          - observationVariableDbId: 85a21ce1 
            observationVariableName: Root color
          - observationVariableDbId: 46f590e5 
            observationVariableName: Virus severity
        

