info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths:
  /traits:
    get:
      summary: Get the Traits
      description: |-
        Call to retrieve a list of traits available in the system and their associated variables.

        An Observation Variable has 3 critical parts; A Trait being observed, a Method for making the observation, and a Scale on which the observation can be measured and compared with other observations.'
      parameters:
      - description: The unique identifier for a trait
        in: query
        name: traitDbId
        required: false
        schema:
          type: string
      - description: The unique identifier for an observation variable
        in: query
        name: observationVariableDbId
        required: false
        schema:
          type: string
      - $ref: '#/components/parameters/ontologyDbId'
      - $ref: '#/components/parameters/commonCropName'
      - $ref: '#/components/parameters/programDbId'
      - $ref: '#/components/parameters/externalReferenceID'
      - $ref: '#/components/parameters/externalReferenceId'
      - $ref: '#/components/parameters/externalReferenceSource'
      - $ref: '#/components/parameters/page'
      - $ref: '#/components/parameters/pageSize'
      - $ref: '#/components/parameters/authorizationHeader'
      responses:
        '200':
          $ref: '#/components/responses/TraitListResponse'
        '400':
          $ref: '#/components/responses/400BadRequest'
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '403':
          $ref: '#/components/responses/403Forbidden'
      tags:
      - Traits
    post:
      summary: Add new Traits
      description: Create new trait objects in the database
      parameters:
      - $ref: '#/components/parameters/authorizationHeader'
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/TraitNewRequest'
      responses:
        '200':
          $ref: '#/components/responses/TraitListResponse'
        '400':
          $ref: '#/components/responses/400BadRequest'
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '403':
          $ref: '#/components/responses/403Forbidden'
      tags:
      - Traits
components:
  responses:
    TraitListResponse:
      content:
        application/json:
          schema:
            title: TraitListResponse
            type: object
            properties:
              '@context':
                $ref: '#/components/schemas/Context'
              metadata:
                $ref: '#/components/schemas/metadata'
              result:
                properties:
                  data:
                    items:
                      $ref: '#/components/schemas/Trait'
                    type: array
                required:
                - data
                type: object
            required:
            - metadata
            - result
      description: OK
      headers: {}
