info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths: {}
components:
  schemas:
    ReferenceSetsSearchRequest:
      allOf:
      - $ref: '#/components/schemas/SearchRequestParametersPaging'
      - $ref: '#/components/schemas/SearchRequestParametersCommonCropNames'
      - $ref: '#/components/schemas/SearchRequestParametersPrograms'
      - $ref: '#/components/schemas/SearchRequestParametersGermplasm'
      - $ref: '#/components/schemas/SearchRequestParametersTrials'
      - $ref: '#/components/schemas/SearchRequestParametersStudies'
      - $ref: '#/components/schemas/SearchRequestParametersExternalReferences'
      - type: object
        properties:
          accessions:
            type: array
            description: If set, return the reference sets for which the `accession` matches this string (case-sensitive, exact match).
            items: 
              type: string
            example: ['A0009283','A0006657'] 
          assemblyPUIs:
            type: array
            description: If set, return the reference sets for which the `assemblyId` matches this string (case-sensitive, exact match).
            items: 
              type: string
            example: ['doi:10.15454/312953986E3', 'doi:10.15454/312953986E3']
          md5checksums: 
            type: array
            description: If set, return the reference sets for which the `md5checksum` matches this string (case-sensitive, exact match).
            items: 
              type: string
            example: ['c2365e900c81a89cf74d83dab60df146']
          referenceSetDbIds:
            type: array
            description: The `ReferenceSets` to search.
            items: 
              type: string
            example: ['32a19dd7', '2c182c18']

