info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths: {}
components:
  schemas:
    ImagingEventSearchRequest:
      allOf:
      - $ref: '#/components/schemas/SearchRequestParametersPaging'
      - $ref: '#/components/schemas/SearchRequestParametersExternalReferences'
      - $ref: '#/components/schemas/SearchRequestParametersCommonCropNames'
      - $ref: '#/components/schemas/SearchRequestParametersPrograms'
      - type: object
        properties:
          imagingEventNames:
            description: Human readable names to search for.
            items:
              type: string
            type: array
            example: ['ImagingEvent 43', 'Tractor in field']
          imagingEventTimeStampRangeEnd:
            description: The latest timestamp to search for.
            format: date-time
            type: string
          imagingEventTimeStampRangeStart:
            description: The earliest timestamp to search for.
            format: date-time
            type: string
          imagingEventDbIds: 
            description: A list of imagingEvent Ids to search for
            items:
              type: string
            type: array
            example: ['564b64a6', '0d122d1d']


