info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths: {}
components:
  schemas:
    GermplasmAttribute: 
      allOf:
      - $ref: '#/components/schemas/GermplasmAttributeNewRequest'
      - properties: 
          attributeDbId:
            description: The ID which uniquely identifies this attribute within the given database server
            type: string
            example: 2f08b902
        required: 
        - attributeDbId
        type: object
        x-brapi-metadata:
          primaryModel: true
          module: BrAPI-Germplasm
          title: GermplasmAttribute
          description: The Trait-Method-Scale definition for a variable, specifically variables related to Germplasm. Similar to an ObservationVariable, but related to a Germplasm instead of an ObservationUnit

