info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths: {}
components:
  schemas:
    Method:
      allOf:
      - $ref: '#/components/schemas/MethodBaseClass'
      - type: object
        x-brapi-metadata:
          primaryModel: true
          module: BrAPI-Phenotyping
          title: Method
        properties:
          methodDbId:
            description: Method unique identifier
            type: string
            example: 0adb2764

