info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths:
  /metabolomics:
    get:
      summary: Get a filtered list of Metabolomics Protocols
      description: Get a filtered list of Metabolomics Protocols
      parameters:
      - name: metabolomicsProtocolDbId
        description: description
        in: query
        required: false
        schema:
          type: string
      - name: observationUnitDbId
        description: description
        in: query
        required: false
        schema:
          type: string
      - $ref: '#/components/parameters/externalReferenceID'
      - $ref: '#/components/parameters/externalReferenceSource'
      - $ref: '#/components/parameters/page'
      - $ref: '#/components/parameters/pageSize'
      - $ref: '#/components/parameters/authorizationHeader'
      responses:
        '200':
          $ref: '#/components/responses/MetabolomicsProtocolListResponse'
        '400':
          $ref: '#/components/responses/400BadRequest'
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '403':
          $ref: '#/components/responses/403Forbidden'
      tags:
      - High-Dimensional-Phenotypes
#    post:
#      summary: Add a new Metabolomics Protocol to the database
#      description: Add a new Metabolomics Protocol to the database
#      parameters:
#      - $ref: '#/components/parameters/authorizationHeader'
#      requestBody:
#        content:
#          application/json:
#            schema:
#              type: array
#              items: 
#                $ref: '#/components/schemas/MetabolomicsProtocolNewRequest'
#      responses:
#        '200':
#          $ref: '#/components/responses/MetabolomicsProtocolListResponse'
#        '400':
#          $ref: '#/components/responses/400BadRequest'
#        '401':
#          $ref: '#/components/responses/401Unauthorized'
#        '403':
#          $ref: '#/components/responses/403Forbidden'
#      tags:
#      - High-Dimensional-Phenotypes
components:
  responses:
    MetabolomicsProtocolListResponse:
      content:
        application/json:
          schema:
            title: MetabolomicsProtocolListResponse
            properties:
              '@context':
                $ref: '#/components/schemas/Context'
              metadata:
                $ref: '#/components/schemas/metadata'
              result:
                properties:
                  data:
                    items:
                      $ref: '#/components/schemas/MetabolomicsProtocol'
                    type: array
                required:
                - data
                type: object
            required:
            - metadata
            - result
            type: object
      description: description
      headers: {}
