info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths: {}
components:
  schemas:
    PedigreeSearchRequest: 
      allOf:
      - $ref: '#/components/schemas/SearchRequestParametersPaging'
      - $ref: '#/components/schemas/SearchRequestParametersCommonCropNames'
      - $ref: '#/components/schemas/SearchRequestParametersPrograms'
      - $ref: '#/components/schemas/SearchRequestParametersGermplasm'
      - $ref: '#/components/schemas/SearchRequestParametersTrials'
      - $ref: '#/components/schemas/SearchRequestParametersStudies'
      - $ref: '#/components/schemas/SearchRequestParametersExternalReferences'
      - type: object
        properties: 
          germplasmPUIs:
            description: List of Permanent Unique Identifiers to identify germplasm
            items:
              type: string
            type: array
            example: ['http://pui.per/accession/A0000003', 'http://pui.per/accession/A0000477']
          accessionNumbers:
            description: List unique identifiers for accessions within a genebank
            items:
              type: string
            type: array
            example: ['A0000003', 'A0000477']
          collections:
            description: A specific panel/collection/population name this germplasm belongs to.
            items:
              type: string
            type: array
            example: ['RDP1', 'MDP1']
          familyCodes: 
            description: A familyCode representing the family this germplasm belongs to.
            items:
              type: string
            type: array
            example: ['f0000203', 'fa009965']
          instituteCodes:
            description: |-
              The code for the institute that maintains the material. 
              <br/> MCPD (v2.1) (INSTCODE) 1. FAO WIEWS code of the institute where the accession is maintained. The codes consist of the 3-letter ISO 3166 country code of the country where the institute is located plus a number (e.g. PER001). The current set of institute codes is available from http://www.fao.org/wiews. For those institutes not yet having an FAO Code, or for those with "obsolete" codes, see "Common formatting rules (v)".
            items:
              type: string
            type: array
            example: ['PER001', 'NOR001']
          binomialNames: 
            description: List of the full binomial name (scientific name) to identify a germplasm
            items:
              type: string
            type: array
            example: ['Aspergillus fructus', 'Zea mays']
          genus: 
            description: List of Genus names to identify germplasm
            items:
              type: string
            type: array
            example: ['Aspergillus', 'Zea']
          species:
            description: List of Species names to identify germplasm
            items:
              type: string
            type: array
            example: ['fructus', 'mays']
          synonyms:
            description: List of alternative names or IDs used to reference this germplasm
            items:
              type: string
            type: array
            example: ['variety_1', '2c38f9b6']
          includeParents:
            description: If this parameter is true, include the array of parents in the response
            type: boolean
            example: true
          includeSiblings:
            description: If this parameter is true, include the array of siblings in the response
            type: boolean
            example: true
          includeProgeny:
            description: If this parameter is true, include the array of progeny in the response
            type: boolean
            example: true
          includeFullTree:
            description: If this parameter is true, recursively include ALL of the nodes available in this pedigree tree 
            type: boolean
            example: true
          pedigreeDepth:
            description: Recursively include this number of levels up the tree in the response (parents, grand-parents, great-grand-parents, etc)
            type: integer
            example: 3
          progenyDepth:
            description: Recursively include this number of levels down the tree in the response (children, grand-children, great-grand-children, etc)
            type: integer
            example: 3
